export default [
  {
    id: '3',
    strategyName: 'MEDIA-USDC',
    pair: 'MEDIA-USDC',
    author: 'Francium',
    from: 'Raydium Fusion Pool',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    marketCap: 1333333,
    token0: 'USDC',
    token1: 'MEDIA',
    status: 'active',
    version: 2
  },
  {
    id: '4',
    strategyName: 'COPE-USDC',
    pair: 'COPE-USDC',
    author: 'Francium',
    from: 'Raydium Fusion Pool',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    marketCap: 1333333,
    token0: 'USDC',
    token1: 'COPE',
    status: 'active',
    version: 2
  },
  {
    id: '5',
    strategyName: 'ALEPH-USDC',
    pair: 'ALEPH-USDC',
    author: 'Francium',
    from: 'Raydium Fusion Pool',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    marketCap: 1333333,
    token0: 'USDC',
    token1: 'ALEPH',
    status: 'active',
    version: 2
  },
  {
    id: '7',
    strategyName: 'TULIP-USDC',
    pair: 'TULIP-USDC',
    author: 'Francium',
    from: 'Raydium Fusion Pool',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    marketCap: 1333333,
    token0: 'USDC',
    token1: 'TULIP',
    status: 'active',
    version: 2
  },
  {
    id: '8',
    strategyName: 'SNY-USDC',
    pair: 'SNY-USDC',
    author: 'Francium',
    from: 'Raydium Fusion Pool',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    marketCap: 1333333,
    token0: 'USDC',
    token1: 'SNY',
    status: 'active',
    version: 2
  },
  {
    id: '9',
    strategyName: 'SLRS-USDC',
    pair: 'SLRS-USDC',
    author: 'Francium',
    from: 'Raydium Fusion Pool',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    marketCap: 1333333,
    token0: 'USDC',
    token1: 'SLRS',
    status: 'active',
    version: 2
  },
  // {
  //   id: '10',
  //   strategyName: 'STEP-USDC',
  //   pair: 'STEP-USDC',
  //   author: 'Francium',
  //   from: 'Raydium Fusion Pool',
  //   yieldFarmingAPR: 0,
  //   strategyAPR: 0,
  //   tradingFeeAPR: 0,
  //   borrowAPR: 0,
  //   maxLeverage: 3,
  //   minLeverage: 1,
  //   marketCap: 1333333,
  //   token0: 'USDC',
  //   token1: 'STEP',
  //   status: 'active',
  //   version: 2
  // },
  // {
  //   id: '13',
  //   strategyName: 'RAY-USDC',
  //   pair: 'RAY-USDC',
  //   author: 'Francium',
  //   from: 'Raydium Farm Pool',
  //   yieldFarmingAPR: 0,
  //   strategyAPR: 0,
  //   tradingFeeAPR: 0,
  //   borrowAPR: 0,
  //   maxLeverage: 3,
  //   minLeverage: 1,
  //   marketCap: 1333333,
  //   token0: 'USDC',
  //   token1: 'RAY',
  //   status: 'active',
  //   version: 3,
  //   borrowList: ['USDC', 'RAY']
  // },
  {
    id: '11',
    strategyName: 'MNGO-USDC',
    pair: 'MNGO-USDC',
    author: 'Francium',
    from: 'Raydium Fusion Pool',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    marketCap: 1333333,
    token0: 'USDC',
    token1: 'MNGO',
    status: 'active',
    version: 2
  },
  {
    id: '12',
    strategyName: 'LIKE-USDC',
    pair: 'LIKE-USDC',
    author: 'Francium',
    from: 'Raydium Fusion Pool',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    lpDecimal: 9,
    marketCap: 1333333,
    token0: 'USDC',
    token1: 'LIKE',
    status: 'active',
    version: 2
  },
  // {
  //   id: '14',
  //   strategyName: 'RAY-USDT',
  //   pair: 'RAY-USDT',
  //   author: 'Francium',
  //   from: 'Raydium Farm Pool',
  //   yieldFarmingAPR: 0,
  //   strategyAPR: 0,
  //   tradingFeeAPR: 0,
  //   borrowAPR: 0,
  //   maxLeverage: 3,
  //   minLeverage: 1,
  //   marketCap: 1333333,
  //   token0: 'USDT',
  //   token1: 'RAY',
  //   status: 'active',
  //   version: 3,
  //   borrowList: ['USDT', 'RAY']
  // },
  // {
  //   id: '15',
  //   strategyName: 'RAY-SRM',
  //   pair: 'RAY-SRM',
  //   author: 'Francium',
  //   from: 'Raydium Farm Pool',
  //   yieldFarmingAPR: 0,
  //   strategyAPR: 0,
  //   tradingFeeAPR: 0,
  //   borrowAPR: 0,
  //   maxLeverage: 3,
  //   minLeverage: 1,
  //   marketCap: 1333333,
  //   token0: 'SRM',
  //   token1: 'RAY',
  //   status: 'active',
  //   version: 3,
  //   borrowList: ['SRM', 'RAY']
  // },
  // {
  //   id: '16',
  //   strategyName: 'RAY-ETH',
  //   pair: 'RAY-ETH',
  //   author: 'Francium',
  //   from: 'Raydium Farm Pool',
  //   yieldFarmingAPR: 0,
  //   strategyAPR: 0,
  //   tradingFeeAPR: 0,
  //   borrowAPR: 0,
  //   maxLeverage: 3,
  //   minLeverage: 1,
  //   marketCap: 1333333,
  //   token0: 'ETH',
  //   token1: 'RAY',
  //   status: 'active',
  //   version: 3,
  //   borrowList: ['ETH', 'RAY']
  // },
  // {
  //   id: '17',
  //   strategyName: 'RAY-SOL',
  //   pair: 'RAY-SOL',
  //   author: 'Francium',
  //   from: 'Raydium Farm Pool',
  //   yieldFarmingAPR: 0,
  //   strategyAPR: 0,
  //   tradingFeeAPR: 0,
  //   borrowAPR: 0,
  //   maxLeverage: 3,
  //   minLeverage: 1,
  //   marketCap: 1333333,
  //   token0: 'SOL',
  //   token1: 'RAY',
  //   status: 'active',
  //   version: 3,
  //   borrowList: ['SOL', 'RAY']
  // },
  {
    id: '19',
    strategyName: 'ORCA-USDC',
    pair: 'ORCA-USDC',
    author: 'Francium',
    from: 'Orca Aquafarm',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    marketCap: 1333333,
    lpDecimal: 6,
    token0: 'USDC',
    token1: 'ORCA',
    status: 'active',
    version: 3,
    lyfType: 'orca',
    borrowList: ['USDC', 'ORCA'],
    orca: {
      bonus: 4
    },
    isNew: false
  },
  // {
  //   id: '20',
  //   strategyName: 'ETH-SOL',
  //   pair: 'ETH-SOL',
  //   author: 'Francium',
  //   from: 'Orca Aquafarm',
  //   yieldFarmingAPR: 0,
  //   strategyAPR: 0,
  //   tradingFeeAPR: 0,
  //   borrowAPR: 0,
  //   maxLeverage: 3,
  //   minLeverage: 1,
  //   marketCap: 1333333,
  //   lpDecimal: 6,
  //   token0: 'SOL',
  //   token1: 'ETH',
  //   status: 'active',
  //   version: 3,
  //   lyfType: 'orca',
  //   borrowList: ['SOL', 'ETH'],
  //   orca: {
  //     bonus: 1,
  //     tokenBDecimal: 9
  //   }
  // },
  // {
  //   id: '21',
  //   strategyName: 'SOL-USDT',
  //   pair: 'SOL-USDT',
  //   author: 'Francium',
  //   from: 'Orca Aquafarm',
  //   yieldFarmingAPR: 0,
  //   strategyAPR: 0,
  //   tradingFeeAPR: 0,
  //   borrowAPR: 0,
  //   maxLeverage: 3,
  //   minLeverage: 1,
  //   marketCap: 1333333,
  //   lpDecimal: 6,
  //   token0: 'USDT',
  //   token1: 'SOL',
  //   status: 'active',
  //   version: 3,
  //   lyfType: 'orca',
  //   borrowList: ['USDT', 'SOL'],
  //   orca: {
  //     bonus: 1
  //   }
  // },
  // {
  //   id: '22',
  //   strategyName: 'ETH-USDC',
  //   pair: 'ETH-USDC',
  //   author: 'Francium',
  //   from: 'Orca Aquafarm',
  //   yieldFarmingAPR: 0,
  //   strategyAPR: 0,
  //   tradingFeeAPR: 0,
  //   borrowAPR: 0,
  //   maxLeverage: 3,
  //   minLeverage: 1,
  //   marketCap: 1333333,
  //   lpDecimal: 6,
  //   token0: 'USDC',
  //   token1: 'ETH',
  //   status: 'active',
  //   version: 3,
  //   lyfType: 'orca',
  //   borrowList: ['USDC', 'ETH'],
  //   orca: {
  //     bonus: 1
  //   }
  // },
  {
    id: '23',
    strategyName: 'ATLAS-USDC',
    pair: 'ATLAS-USDC',
    author: 'Francium',
    from: 'Raydium Fusion Pool',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    lpDecimal: 8,
    marketCap: 1333333,
    token0: 'USDC',
    token1: 'ATLAS',
    status: 'active',
    version: 3,
    borrowList: ['USDC']
  },
  {
    id: '24',
    strategyName: 'POLIS-USDC',
    pair: 'POLIS-USDC',
    author: 'Francium',
    from: 'Raydium Fusion Pool',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    lpDecimal: 8,
    marketCap: 1333333,
    token0: 'USDC',
    token1: 'POLIS',
    status: 'active',
    version: 3,
    borrowList: ['USDC']
  },
  // {
  //   id: '25',
  //   strategyName: 'USDC-USDT',
  //   pair: 'USDC-USDT',
  //   author: 'Francium',
  //   from: 'Orca Aquafarm',
  //   yieldFarmingAPR: 0,
  //   strategyAPR: 0,
  //   tradingFeeAPR: 0,
  //   borrowAPR: 0,
  //   maxLeverage: 3,
  //   minLeverage: 1,
  //   marketCap: 1333333,
  //   lpDecimal: 6,
  //   token0: 'USDT',
  //   token1: 'USDC',
  //   status: 'active',
  //   version: 3,
  //   lyfType: 'orca',
  //   borrowList: ['USDC', 'USDT'],
  //   showOrigin: true,
  //   orca: {
  //     bonus: 1.5,
  //     poolKey: 'USDC/USDT[stable][aquafarm]'
  //   }
  // },
  {
    id: '26',
    strategyName: 'ORCA-SOL',
    pair: 'ORCA-SOL',
    author: 'Francium',
    from: 'Orca Aquafarm',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    marketCap: 1333333,
    lpDecimal: 6,
    token0: 'SOL',
    token1: 'ORCA',
    status: 'active',
    version: 3,
    lyfType: 'orca',
    borrowList: ['SOL', 'ORCA'],
    orca: {
      bonus: 4,
      tokenBDecimal: 9
    },
    isNew: false
  },
  {
    id: '18',
    strategyName: 'SOL-USDC',
    pair: 'SOL-USDC',
    author: 'Francium',
    from: 'Orca Aquafarm',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    marketCap: 1333333,
    lpDecimal: 6,
    token0: 'USDC',
    token1: 'SOL',
    status: 'active',
    version: 3,
    lyfType: 'orca',
    borrowList: ['USDC', 'SOL'],
    orca: {
      tokenBDecimal: 6
    },
    isNew: false
  },
  {
    id: '27',
    strategyName: 'ATLAS-USDC',
    pair: 'ATLAS-USDC',
    alias: 'ATLAS-USDC[Double-Dip]',
    author: 'Francium',
    from: 'Orca Double-Dip',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    marketCap: 1333333,
    lpDecimal: 6,
    token0: 'USDC',
    token1: 'ATLAS',
    status: 'active',
    version: 3,
    lyfType: 'orca',
    borrowList: ['USDC'],
    orca: {
      tokenBDecimal: 6,
      isDoubleDip: true,
      // poolKey: 'USDC/USDT[stable][aquafarm]'
    },
    isNew: true
  },
  {
    id: '27',
    strategyName: 'POLIS-USDC',
    pair: 'POLIS-USDC',
    alias: 'POLIS-USDC[Double-Dip]',
    author: 'Francium',
    from: 'Orca Double-Dip',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    marketCap: 1333333,
    lpDecimal: 6,
    token0: 'USDC',
    token1: 'POLIS',
    status: 'active',
    version: 3,
    lyfType: 'orca',
    borrowList: ['USDC'],
    orca: {
      tokenBDecimal: 6,
      isDoubleDip: true
      // poolKey: 'USDC/USDT[stable][aquafarm]'
    },
    isNew: true
  },
  {
    id: '32',
    strategyName: 'GRAPE-USDC',
    pair: 'GRAPE-USDC',
    author: 'Francium',
    from: 'Raydium Fusion Pool',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    lpDecimal: 6,
    marketCap: 1333333,
    token0: 'USDC',
    token1: 'GRAPE',
    status: 'active',
    version: 3,
    borrowList: ['USDC'],
    isNew: true
  },
];
