export const strategyList = [
  {
    id: 'F001',
    strategyName: 'whETH-USDC-Strategy0',
    pair: 'whETH-USDC-Strategy0',
    alias: 'whETH-USDC',
    author: 'Francium',
    from: 'Orca Aquafarm',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    marketCap: 1333333,
    lpDecimal: 6,
    token0: 'USDC',
    token1: 'whETH',
    status: 'active',
    version: 3,
    lyfType: 'orca',
    borrowList: ['USDC', 'whETH'],
    orca: {
      tokenBDecimal: 6,
      poolKey: 'whETH/USDC[aquafarm]'
    },
    isNew: true
  },
  {
    id: 'F002',
    strategyName: 'whETH-USDC-Strategy-1',
    alias: 'whETH-USDC[Raydium]',
    pair: 'whETH-USDC-Strategy-1',
    author: 'Francium',
    from: 'Raydium Fusion Pool',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    lpDecimal: 8,
    marketCap: 1333333,
    token0: 'USDC',
    token1: 'whETH',
    status: 'active',
    version: 3,
    borrowList: ['USDC', 'whETH'],
    isNew: true
  },
];

export default [
  ...strategyList,
  {
    id: '3',
    strategyName: 'MEDIA-USDC',
    pair: 'MEDIA-USDC',
    author: 'Francium',
    from: 'Raydium Fusion Pool',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    marketCap: 1333333,
    token0: 'USDC',
    token1: 'MEDIA',
    status: 'active',
    version: 2
  },
  {
    id: '4',
    strategyName: 'COPE-USDC',
    pair: 'COPE-USDC',
    author: 'Francium',
    from: 'Raydium Fusion Pool',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    marketCap: 1333333,
    token0: 'USDC',
    token1: 'COPE',
    status: 'active',
    version: 2
  },
  {
    id: '5',
    strategyName: 'ALEPH-USDC',
    pair: 'ALEPH-USDC',
    author: 'Francium',
    from: 'Raydium Fusion Pool',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    marketCap: 1333333,
    token0: 'USDC',
    token1: 'ALEPH',
    status: 'active',
    version: 2
  },
  {
    id: '7',
    strategyName: 'TULIP-USDC',
    pair: 'TULIP-USDC',
    author: 'Francium',
    from: 'Raydium Fusion Pool',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    marketCap: 1333333,
    token0: 'USDC',
    token1: 'TULIP',
    status: 'active',
    version: 2
  },
  {
    id: '8',
    strategyName: 'SNY-USDC',
    pair: 'SNY-USDC',
    author: 'Francium',
    from: 'Raydium Fusion Pool',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    marketCap: 1333333,
    token0: 'USDC',
    token1: 'SNY',
    status: 'active',
    version: 2
  },
  {
    id: '9',
    strategyName: 'SLRS-USDC',
    pair: 'SLRS-USDC',
    author: 'Francium',
    from: 'Raydium Fusion Pool',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    marketCap: 1333333,
    token0: 'USDC',
    token1: 'SLRS',
    status: 'active',
    version: 2
  },
  // {
  //   id: '10',
  //   strategyName: 'STEP-USDC',
  //   pair: 'STEP-USDC',
  //   author: 'Francium',
  //   from: 'Raydium Fusion Pool',
  //   yieldFarmingAPR: 0,
  //   strategyAPR: 0,
  //   tradingFeeAPR: 0,
  //   borrowAPR: 0,
  //   maxLeverage: 3,
  //   minLeverage: 1,
  //   marketCap: 1333333,
  //   token0: 'USDC',
  //   token1: 'STEP',
  //   status: 'active',
  //   version: 2
  // },
  // {
  //   id: '13',
  //   strategyName: 'RAY-USDC',
  //   pair: 'RAY-USDC',
  //   author: 'Francium',
  //   from: 'Raydium Farm Pool',
  //   yieldFarmingAPR: 0,
  //   strategyAPR: 0,
  //   tradingFeeAPR: 0,
  //   borrowAPR: 0,
  //   maxLeverage: 3,
  //   minLeverage: 1,
  //   marketCap: 1333333,
  //   token0: 'USDC',
  //   token1: 'RAY',
  //   status: 'active',
  //   version: 3,
  //   borrowList: ['USDC', 'RAY']
  // },
  {
    id: '11',
    strategyName: 'MNGO-USDC',
    pair: 'MNGO-USDC',
    author: 'Francium',
    from: 'Raydium Fusion Pool',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    marketCap: 1333333,
    token0: 'USDC',
    token1: 'MNGO',
    status: 'active',
    version: 2
  },
  {
    id: '12',
    strategyName: 'LIKE-USDC',
    pair: 'LIKE-USDC',
    author: 'Francium',
    from: 'Raydium Fusion Pool',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    lpDecimal: 9,
    marketCap: 1333333,
    token0: 'USDC',
    token1: 'LIKE',
    status: 'active',
    version: 2
  },
  // {
  //   id: '14',
  //   strategyName: 'RAY-USDT',
  //   pair: 'RAY-USDT',
  //   author: 'Francium',
  //   from: 'Raydium Farm Pool',
  //   yieldFarmingAPR: 0,
  //   strategyAPR: 0,
  //   tradingFeeAPR: 0,
  //   borrowAPR: 0,
  //   maxLeverage: 3,
  //   minLeverage: 1,
  //   marketCap: 1333333,
  //   token0: 'USDT',
  //   token1: 'RAY',
  //   status: 'active',
  //   version: 3,
  //   borrowList: ['USDT', 'RAY']
  // },
  // {
  //   id: '15',
  //   strategyName: 'RAY-SRM',
  //   pair: 'RAY-SRM',
  //   author: 'Francium',
  //   from: 'Raydium Farm Pool',
  //   yieldFarmingAPR: 0,
  //   strategyAPR: 0,
  //   tradingFeeAPR: 0,
  //   borrowAPR: 0,
  //   maxLeverage: 3,
  //   minLeverage: 1,
  //   marketCap: 1333333,
  //   token0: 'SRM',
  //   token1: 'RAY',
  //   status: 'active',
  //   version: 3,
  //   borrowList: ['SRM', 'RAY']
  // },
  // {
  //   id: '16',
  //   strategyName: 'RAY-ETH',
  //   pair: 'RAY-ETH',
  //   author: 'Francium',
  //   from: 'Raydium Farm Pool',
  //   yieldFarmingAPR: 0,
  //   strategyAPR: 0,
  //   tradingFeeAPR: 0,
  //   borrowAPR: 0,
  //   maxLeverage: 3,
  //   minLeverage: 1,
  //   marketCap: 1333333,
  //   token0: 'ETH',
  //   token1: 'RAY',
  //   status: 'active',
  //   version: 3,
  //   borrowList: ['ETH', 'RAY']
  // },
  // {
  //   id: '17',
  //   strategyName: 'RAY-SOL',
  //   pair: 'RAY-SOL',
  //   author: 'Francium',
  //   from: 'Raydium Farm Pool',
  //   yieldFarmingAPR: 0,
  //   strategyAPR: 0,
  //   tradingFeeAPR: 0,
  //   borrowAPR: 0,
  //   maxLeverage: 3,
  //   minLeverage: 1,
  //   marketCap: 1333333,
  //   token0: 'SOL',
  //   token1: 'RAY',
  //   status: 'active',
  //   version: 3,
  //   borrowList: ['SOL', 'RAY']
  // },
  {
    id: '19',
    strategyName: 'ORCA-USDC',
    pair: 'ORCA-USDC',
    author: 'Francium',
    from: 'Orca Aquafarm',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    marketCap: 1333333,
    lpDecimal: 6,
    token0: 'USDC',
    token1: 'ORCA',
    status: 'active',
    version: 3,
    lyfType: 'orca',
    borrowList: ['USDC', 'ORCA'],
    orca: {
      bonus: 4
    },
    isNew: false
  },
  // {
  //   id: '20',
  //   strategyName: 'ETH-SOL',
  //   pair: 'ETH-SOL',
  //   author: 'Francium',
  //   from: 'Orca Aquafarm',
  //   yieldFarmingAPR: 0,
  //   strategyAPR: 0,
  //   tradingFeeAPR: 0,
  //   borrowAPR: 0,
  //   maxLeverage: 3,
  //   minLeverage: 1,
  //   marketCap: 1333333,
  //   lpDecimal: 6,
  //   token0: 'SOL',
  //   token1: 'ETH',
  //   status: 'active',
  //   version: 3,
  //   lyfType: 'orca',
  //   borrowList: ['SOL', 'ETH'],
  //   orca: {
  //     bonus: 1,
  //     tokenBDecimal: 9
  //   }
  // },
  // {
  //   id: '21',
  //   strategyName: 'SOL-USDT',
  //   pair: 'SOL-USDT',
  //   author: 'Francium',
  //   from: 'Orca Aquafarm',
  //   yieldFarmingAPR: 0,
  //   strategyAPR: 0,
  //   tradingFeeAPR: 0,
  //   borrowAPR: 0,
  //   maxLeverage: 3,
  //   minLeverage: 1,
  //   marketCap: 1333333,
  //   lpDecimal: 6,
  //   token0: 'USDT',
  //   token1: 'SOL',
  //   status: 'active',
  //   version: 3,
  //   lyfType: 'orca',
  //   borrowList: ['USDT', 'SOL'],
  //   orca: {
  //     bonus: 1
  //   }
  // },
  // {
  //   id: '22',
  //   strategyName: 'ETH-USDC',
  //   pair: 'ETH-USDC',
  //   author: 'Francium',
  //   from: 'Orca Aquafarm',
  //   yieldFarmingAPR: 0,
  //   strategyAPR: 0,
  //   tradingFeeAPR: 0,
  //   borrowAPR: 0,
  //   maxLeverage: 3,
  //   minLeverage: 1,
  //   marketCap: 1333333,
  //   lpDecimal: 6,
  //   token0: 'USDC',
  //   token1: 'ETH',
  //   status: 'active',
  //   version: 3,
  //   lyfType: 'orca',
  //   borrowList: ['USDC', 'ETH'],
  //   orca: {
  //     bonus: 1
  //   }
  // },
  {
    id: '23',
    strategyName: 'ATLAS-USDC',
    pair: 'ATLAS-USDC',
    author: 'Francium',
    from: 'Raydium Fusion Pool',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    lpDecimal: 8,
    marketCap: 1333333,
    token0: 'USDC',
    token1: 'ATLAS',
    status: 'active',
    version: 3,
    borrowList: ['USDC']
  },
  {
    id: '24',
    strategyName: 'POLIS-USDC',
    pair: 'POLIS-USDC',
    author: 'Francium',
    from: 'Raydium Fusion Pool',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    lpDecimal: 8,
    marketCap: 1333333,
    token0: 'USDC',
    token1: 'POLIS',
    status: 'active',
    version: 3,
    borrowList: ['USDC']
  },
  // {
  //   id: '25',
  //   strategyName: 'USDC-USDT',
  //   pair: 'USDC-USDT',
  //   author: 'Francium',
  //   from: 'Orca Aquafarm',
  //   yieldFarmingAPR: 0,
  //   strategyAPR: 0,
  //   tradingFeeAPR: 0,
  //   borrowAPR: 0,
  //   maxLeverage: 3,
  //   minLeverage: 1,
  //   marketCap: 1333333,
  //   lpDecimal: 6,
  //   token0: 'USDT',
  //   token1: 'USDC',
  //   status: 'active',
  //   version: 3,
  //   lyfType: 'orca',
  //   borrowList: ['USDC', 'USDT'],
  //   showOrigin: true,
  //   orca: {
  //     bonus: 1.5,
  //     poolKey: 'USDC/USDT[stable][aquafarm]'
  //   }
  // },
  {
    id: '26',
    strategyName: 'ORCA-SOL',
    pair: 'ORCA-SOL',
    author: 'Francium',
    from: 'Orca Aquafarm',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    marketCap: 1333333,
    lpDecimal: 6,
    token0: 'SOL',
    token1: 'ORCA',
    status: 'active',
    version: 3,
    lyfType: 'orca',
    borrowList: ['SOL', 'ORCA'],
    orca: {
      bonus: 4,
      tokenBDecimal: 9
    },
    isNew: false
  },
  {
    id: '18',
    strategyName: 'SOL-USDC',
    pair: 'SOL-USDC',
    author: 'Francium',
    from: 'Orca Aquafarm',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    marketCap: 1333333,
    lpDecimal: 6,
    token0: 'USDC',
    token1: 'SOL',
    status: 'active',
    version: 3,
    lyfType: 'orca',
    borrowList: ['USDC', 'SOL'],
    orca: {
      tokenBDecimal: 6
    },
    isNew: false
  },
  {
    id: '27',
    strategyName: 'ATLAS-USDC',
    pair: 'ATLAS-USDC',
    alias: 'ATLAS-USDC[Double-Dip]',
    author: 'Francium',
    from: 'Orca Double-Dip',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    marketCap: 1333333,
    lpDecimal: 6,
    token0: 'USDC',
    token1: 'ATLAS',
    status: 'active',
    version: 3,
    lyfType: 'orca',
    borrowList: ['USDC'],
    orca: {
      tokenBDecimal: 6,
      isDoubleDip: true,
      // poolKey: 'USDC/USDT[stable][aquafarm]'
    },
    isNew: true
  },
  {
    id: '27',
    strategyName: 'POLIS-USDC',
    pair: 'POLIS-USDC',
    alias: 'POLIS-USDC[Double-Dip]',
    author: 'Francium',
    from: 'Orca Double-Dip',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    marketCap: 1333333,
    lpDecimal: 6,
    token0: 'USDC',
    token1: 'POLIS',
    status: 'active',
    version: 3,
    lyfType: 'orca',
    borrowList: ['USDC'],
    orca: {
      tokenBDecimal: 6,
      isDoubleDip: true
      // poolKey: 'USDC/USDT[stable][aquafarm]'
    },
    isNew: true
  },
  {
    id: '32',
    strategyName: 'GRAPE-USDC',
    pair: 'GRAPE-USDC',
    author: 'Francium',
    from: 'Raydium Fusion Pool',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    lpDecimal: 6,
    marketCap: 1333333,
    token0: 'USDC',
    token1: 'GRAPE',
    status: 'active',
    version: 3,
    borrowList: ['USDC'],
    isNew: true
  },
  {
    id: '33',
    strategyName: 'ORCA-mSOL',
    pair: 'ORCA-mSOL',
    author: 'Francium',
    from: 'Orca Double-Dip',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    marketCap: 1333333,
    lpDecimal: 6,
    token0: 'mSOL',
    token1: 'ORCA',
    status: 'active',
    version: 3,
    lyfType: 'orca',
    borrowList: ['mSOL', 'ORCA'],
    orca: {
      tokenBDecimal: 9,
      isDoubleDip: true,
      poolKey: 'ORCA/mSOL[aquafarm]'
    },
    isNew: true
  },
  {
    id: '34',
    strategyName: 'mSOL-USDC',
    pair: 'mSOL-USDC',
    // alias: 'MSOL-USDC[Double-Dip]',
    author: 'Francium',
    from: 'Orca Double-Dip',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    marketCap: 1333333,
    lpDecimal: 6,
    token0: 'USDC',
    token1: 'mSOL',
    status: 'active',
    version: 3,
    lyfType: 'orca',
    borrowList: ['USDC', 'mSOL'],
    orca: {
      tokenBDecimal: 6,
      isDoubleDip: true,
      poolKey: 'mSOL/USDC[aquafarm]'
    },
    isNew: true
  },
  {
    id: '35',
    strategyName: 'mSOL-USDT',
    pair: 'mSOL-USDT',
    // alias: 'MSOL-USDC[Double-Dip]',
    author: 'Francium',
    from: 'Orca Double-Dip',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    marketCap: 1333333,
    lpDecimal: 6,
    token0: 'USDT',
    token1: 'mSOL',
    status: 'active',
    version: 3,
    lyfType: 'orca',
    borrowList: ['USDT', 'mSOL'],
    orca: {
      tokenBDecimal: 6,
      isDoubleDip: true,
      poolKey: 'mSOL/USDT[aquafarm]'
    },
    isNew: true
  },
  {
    id: '37',
    strategyName: 'NINJA-SOL',
    pair: 'NINJA-SOL',
    author: 'Francium',
    from: 'Orca Double-Dip',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    marketCap: 1333333,
    lpDecimal: 6,
    token0: 'SOL',
    token1: 'NINJA',
    status: 'active',
    version: 3,
    lyfType: 'orca',
    borrowList: ['SOL'],
    orca: {
      tokenBDecimal: 9,
      isDoubleDip: true,
      rewardToken: 'NINJA',
      rewardDecimal: 6,
      poolKey: 'NINJA/SOL[aquafarm]'
    },
    isNew: true
  },
  {
    id: '20',
    strategyName: 'ETH-SOL',
    pair: 'ETH-SOL',
    author: 'Francium',
    from: 'Orca Aquafarm',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    marketCap: 1333333,
    lpDecimal: 6,
    token0: 'SOL',
    token1: 'ETH',
    status: 'active',
    version: 3,
    lyfType: 'orca',
    borrowList: ['SOL', 'ETH'],
    orca: {
      bonus: 1,
      tokenBDecimal: 9
    },
    isNew: true
  },
  {
    id: '36',
    strategyName: 'BTC-mSOL',
    pair: 'BTC-mSOL',
    author: 'Francium',
    from: 'Orca Double-Dip',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    marketCap: 1333333,
    lpDecimal: 6,
    token0: 'mSOL',
    token1: 'BTC',
    status: 'active',
    version: 3,
    lyfType: 'orca',
    borrowList: ['mSOL', 'BTC'],
    orca: {
      tokenBDecimal: 9,
      isDoubleDip: true,
      rewardToken: 'MNDE',
      rewardDecimal: 9,
      poolKey: 'BTC/mSOL[aquafarm]'
    },
    isNew: true
  },

  {
    id: '38',
    strategyName: 'whETH-USDC',
    pair: 'whETH-USDC',
    author: 'Francium',
    from: 'Orca Aquafarm',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    marketCap: 1333333,
    lpDecimal: 6,
    token0: 'USDC',
    token1: 'whETH',
    status: 'active',
    version: 3,
    lyfType: 'orca',
    borrowList: ['USDC', 'whETH'],
    orca: {
      tokenBDecimal: 6,
      poolKey: 'whETH/USDC[aquafarm]'
    },
    isNew: true
  },
  {
    id: '39',
    strategyName: 'mSOL-whETH',
    pair: 'mSOL-whETH',
    // alias: 'MSOL-whETH[Double-Dip]',
    author: 'Francium',
    from: 'Orca Double-Dip',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    marketCap: 1333333,
    lpDecimal: 6,
    token0: 'whETH',
    token1: 'mSOL',
    status: 'active',
    version: 3,
    lyfType: 'orca',
    borrowList: ['mSOL', 'whETH'],
    orca: {
      tokenBDecimal: 8,
      isDoubleDip: true,
      rewardToken: 'MNDE',
      rewardDecimal: 9,
      poolKey: 'mSOL/whETH[aquafarm]'
    },
    isNew: true
  },
  {
    id: '40',
    strategyName: 'whETH-SOL',
    pair: 'whETH-SOL',
    author: 'Francium',
    from: 'Orca Aquafarm',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    marketCap: 1333333,
    lpDecimal: 6,
    token0: 'SOL',
    token1: 'whETH',
    status: 'active',
    version: 3,
    lyfType: 'orca',
    borrowList: ['SOL', 'whETH'],
    orca: {
      tokenBDecimal: 9,
      poolKey: 'whETH/SOL[aquafarm]'
    },
    isNew: true
  },
  {
    id: '41',
    strategyName: 'SBR-USDC',
    pair: 'SBR-USDC',
    author: 'Francium',
    from: 'Orca Aquafarm',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    marketCap: 1333333,
    lpDecimal: 6,
    token0: 'USDC',
    token1: 'SBR',
    status: 'active',
    version: 3,
    lyfType: 'orca',
    borrowList: ['USDC'],
    orca: {
      tokenBDecimal: 6,
      poolKey: 'SBR/USDC[aquafarm]'
    },
    isNew: true
  },

  {
    id: '42',
    strategyName: 'LIQ-USDC',
    pair: 'LIQ-USDC',
    author: 'Francium',
    from: 'Orca Double-Dip',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    marketCap: 1333333,
    lpDecimal: 6,
    token0: 'USDC',
    token1: 'LIQ',
    status: 'active',
    version: 3,
    lyfType: 'orca',
    borrowList: ['USDC'],
    orca: {
      tokenBDecimal: 6,
      isDoubleDip: true,
      rewardToken: 'LIQ',
      rewardDecimal: 6,
      poolKey: 'LIQ/USDC[aquafarm]'
    },
    isNew: true
  },
  {
    id: '43',
    strategyName: 'SAMO-USDC',
    pair: 'SAMO-USDC',
    author: 'Francium',
    from: 'Orca Double-Dip',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    marketCap: 1333333,
    lpDecimal: 6,
    token0: 'USDC',
    token1: 'SAMO',
    status: 'active',
    version: 3,
    lyfType: 'orca',
    borrowList: ['USDC'],
    orca: {
      tokenBDecimal: 6,
      isDoubleDip: true,
      rewardToken: 'SAMO',
      rewardDecimal: 9,
      poolKey: 'SAMO/USDC[aquafarm]'
    },
    isNew: true
  },
  {
    id: '44',
    strategyName: 'PORT-USDC',
    pair: 'PORT-USDC',
    author: 'Francium',
    from: 'Orca Double-Dip',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    marketCap: 1333333,
    lpDecimal: 6,
    token0: 'USDC',
    token1: 'PORT',
    status: 'active',
    version: 3,
    lyfType: 'orca',
    borrowList: ['USDC'],
    orca: {
      tokenBDecimal: 6,
      isDoubleDip: true,
      rewardToken: 'PORT',
      rewardDecimal: 6,
      poolKey: 'PORT/USDC[aquafarm]'
    },
    isNew: true
  },
  {
    id: '45',
    strategyName: 'ABR-USDC',
    pair: 'ABR-USDC',
    author: 'Francium',
    from: 'Orca Double-Dip',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    marketCap: 1333333,
    lpDecimal: 6,
    token0: 'USDC',
    token1: 'ABR',
    status: 'active',
    version: 3,
    lyfType: 'orca',
    borrowList: ['USDC'],
    orca: {
      tokenBDecimal: 6,
      isDoubleDip: true,
      rewardToken: 'ABR',
      rewardDecimal: 9,
      poolKey: 'ABR/USDC[aquafarm]'
    },
    isNew: true
  },
  {
    id: '46',
    strategyName: 'COPE-USDC',
    alias: 'COPE-USDC[Double-Dip]',
    pair: 'COPE-USDC',
    author: 'Francium',
    from: 'Orca Double-Dip',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    marketCap: 1333333,
    lpDecimal: 6,
    token0: 'USDC',
    token1: 'COPE',
    status: 'active',
    version: 3,
    lyfType: 'orca',
    borrowList: ['USDC'],
    orca: {
      tokenBDecimal: 6,
      isDoubleDip: true,
      rewardToken: 'COPE',
      rewardDecimal: 6,
      poolKey: 'COPE/USDC[aquafarm]'
    },
    isNew: true
  },

  {
    id: '47',
    strategyName: 'RAY-USDC',
    pair: 'RAY-USDC',
    author: 'Francium',
    from: 'Raydium Fusion Pool',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    lpDecimal: 6,
    marketCap: 1333333,
    token0: 'USDC',
    token1: 'RAY',
    status: 'active',
    version: 3,
    borrowList: ['USDC', 'RAY'],
    isNew: true
  },
  {
    id: '48',
    strategyName: 'RAY-USDT',
    pair: 'RAY-USDT',
    author: 'Francium',
    from: 'Raydium Fusion Pool',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    lpDecimal: 6,
    marketCap: 1333333,
    token0: 'USDT',
    token1: 'RAY',
    status: 'active',
    version: 3,
    borrowList: ['USDT', 'RAY'],
    isNew: true
  },
  {
    id: '49',
    strategyName: 'RAY-SOL',
    pair: 'RAY-SOL',
    author: 'Francium',
    from: 'Raydium Fusion Pool',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    lpDecimal: 9,
    marketCap: 1333333,
    token0: 'SOL',
    token1: 'RAY',
    status: 'active',
    version: 3,
    borrowList: ['SOL', 'RAY'],
    isNew: true
  },
  {
    id: '50',
    strategyName: 'RAY-SRM',
    pair: 'RAY-SRM',
    author: 'Francium',
    from: 'Raydium Fusion Pool',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    lpDecimal: 6,
    marketCap: 1333333,
    token0: 'SRM',
    token1: 'RAY',
    status: 'active',
    version: 3,
    borrowList: ['RAY'],
    isNew: true
  },
  {
    id: '51',
    strategyName: 'RAY-ETH',
    pair: 'RAY-ETH',
    author: 'Francium',
    from: 'Raydium Fusion Pool',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    lpDecimal: 6,
    marketCap: 1333333,
    token0: 'ETH',
    token1: 'RAY',
    status: 'active',
    version: 3,
    borrowList: ['ETH', 'RAY'],
    isNew: true
  },
  {
    id: '52',
    strategyName: 'FTT-USDC',
    pair: 'FTT-USDC',
    author: 'Francium',
    from: 'Orca Aquafarm',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    marketCap: 1333333,
    lpDecimal: 6,
    token0: 'USDC',
    token1: 'FTT',
    status: 'active',
    version: 3,
    lyfType: 'orca',
    borrowList: ['USDC'],
    orca: {
      tokenBDecimal: 6,
      poolKey: 'FTT/USDC[aquafarm]'
    },
    isNew: true
  },
  {
    id: '53',
    strategyName: 'SRM-SOL',
    pair: 'SRM-SOL',
    author: 'Francium',
    from: 'Orca Aquafarm',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    marketCap: 1333333,
    lpDecimal: 6,
    token0: 'SOL',
    token1: 'SRM',
    status: 'active',
    version: 3,
    lyfType: 'orca',
    borrowList: ['SOL'],
    orca: {
      tokenBDecimal: 9,
      poolKey: 'SRM/SOL[aquafarm]'
    },
    isNew: true
  },
  {
    id: '54',
    strategyName: 'COPE-SOL',
    pair: 'COPE-SOL',
    author: 'Francium',
    from: 'Orca Aquafarm',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    marketCap: 1333333,
    lpDecimal: 6,
    token0: 'SOL',
    token1: 'COPE',
    status: 'active',
    version: 3,
    lyfType: 'orca',
    borrowList: ['SOL'],
    orca: {
      tokenBDecimal: 9,
      poolKey: 'COPE/SOL[aquafarm]'
    },
    isNew: true
  },
  {
    id: '55',
    strategyName: 'mSOL-SOL',
    pair: 'mSOL-SOL',
    author: 'Francium',
    from: 'Orca Double-Dip',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    marketCap: 1333333,
    lpDecimal: 6,
    token0: 'SOL',
    token1: 'mSOL',
    status: 'active',
    version: 3,
    lyfType: 'orca',
    borrowList: ['SOL', 'mSOL'],
    orca: {
      tokenBDecimal: 9,
      isDoubleDip: true,
      rewardToken: 'MNDE',
      rewardDecimal: 9,
      poolKey: 'mSOL/SOL[stable][aquafarm]'
    },
    isNew: true
  },
  {
    id: '56',
    strategyName: 'SRM-USDC',
    pair: 'SRM-USDC',
    author: 'Francium',
    from: 'Raydium Fusion Pool',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    lpDecimal: 6,
    marketCap: 1333333,
    token0: 'USDC',
    token1: 'SRM',
    status: 'active',
    version: 3,
    borrowList: ['USDC', 'SRM'],
    isNew: true
  },

  {
    id: '57',
    strategyName: 'whETH-USDC',
    alias: 'whETH-USDC[Raydium]',
    pair: 'whETH-USDC',
    author: 'Francium',
    from: 'Raydium Fusion Pool',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    lpDecimal: 8,
    marketCap: 1333333,
    token0: 'USDC',
    token1: 'whETH',
    status: 'active',
    version: 3,
    borrowList: ['USDC', 'whETH'],
    isNew: true
  },

  {
    id: '58',
    strategyName: 'whETH-SOL',
    pair: 'whETH-SOL',
    alias: 'whETH-SOL[Raydium]',
    author: 'Francium',
    from: 'Raydium Fusion Pool',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    lpDecimal: 8,
    marketCap: 1333333,
    token0: 'SOL',
    token1: 'whETH',
    status: 'active',
    version: 3,
    borrowList: ['SOL', 'whETH'],
    isNew: true
  },

  {
    id: '59',
    strategyName: 'weSUSHI-USDC',
    pair: 'weSUSHI-USDC',
    author: 'Francium',
    from: 'Raydium Fusion Pool',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    lpDecimal: 8,
    marketCap: 1333333,
    token0: 'USDC',
    token1: 'weSUSHI',
    status: 'active',
    version: 3,
    borrowList: ['USDC'],
    isNew: true
  },

  {
    id: '60',
    strategyName: 'weUNI-USDC',
    pair: 'weUNI-USDC',
    author: 'Francium',
    from: 'Raydium Fusion Pool',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    lpDecimal: 8,
    marketCap: 1333333,
    token0: 'USDC',
    token1: 'weUNI',
    status: 'active',
    version: 3,
    borrowList: ['USDC'],
    isNew: true
  },
  {
    id: '61',
    strategyName: 'STARS-USDC',
    pair: 'STARS-USDC',
    author: 'Francium',
    from: 'Raydium Fusion Pool',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    lpDecimal: 6,
    marketCap: 1333333,
    token0: 'USDC',
    token1: 'STARS',
    status: 'active',
    version: 3,
    borrowList: ['USDC'],
    isNew: true
  },

  {
    id: '62',
    strategyName: 'weDYDX-USDC',
    pair: 'weDYDX-USDC',
    author: 'Francium',
    from: 'Raydium Fusion Pool',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    lpDecimal: 8,
    marketCap: 1333333,
    token0: 'USDC',
    token1: 'weDYDX',
    status: 'active',
    version: 3,
    borrowList: ['USDC'],
    isNew: true
  },

  {
    id: '63',
    strategyName: 'weAXS-USDC',
    pair: 'weAXS-USDC',
    author: 'Francium',
    from: 'Raydium Fusion Pool',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    lpDecimal: 8,
    marketCap: 1333333,
    token0: 'USDC',
    token1: 'weAXS',
    status: 'active',
    version: 3,
    borrowList: ['USDC'],
    isNew: true
  },

  {
    id: '64',
    strategyName: 'weSHIB-USDC',
    pair: 'weSHIB-USDC',
    author: 'Francium',
    from: 'Raydium Fusion Pool',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    lpDecimal: 8,
    marketCap: 1333333,
    token0: 'USDC',
    token1: 'weSHIB',
    status: 'active',
    version: 3,
    borrowList: ['USDC'],
    isNew: true
  },
  {
    id: '65',
    strategyName: 'SLND-USDC',
    pair: 'SLND-USDC',
    author: 'Francium',
    from: 'Orca Aquafarm',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    marketCap: 1333333,
    lpDecimal: 6,
    token0: 'USDC',
    token1: 'SLND',
    status: 'active',
    version: 3,
    lyfType: 'orca',
    borrowList: ['USDC'],
    orca: {
      tokenBDecimal: 6,
      poolKey: 'SLND/USDC[aquafarm]'
    },
    isNew: true
  },

  {
    id: '66',
    strategyName: 'weMANA-USDC',
    pair: 'weMANA-USDC',
    author: 'Francium',
    from: 'Raydium Fusion Pool',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    lpDecimal: 8,
    marketCap: 1333333,
    token0: 'USDC',
    token1: 'weMANA',
    status: 'active',
    version: 3,
    borrowList: ['USDC'],
    isNew: true
  },

  {
    id: '67',
    strategyName: 'weSAND-USDC',
    pair: 'weSAND-USDC',
    author: 'Francium',
    from: 'Raydium Fusion Pool',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    lpDecimal: 8,
    marketCap: 1333333,
    token0: 'USDC',
    token1: 'weSAND',
    status: 'active',
    version: 3,
    borrowList: ['USDC'],
    isNew: true
  },

  {
    id: '68',
    strategyName: 'CAVE-USDC',
    pair: 'CAVE-USDC',
    author: 'Francium',
    from: 'Raydium Fusion Pool',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    lpDecimal: 6,
    marketCap: 1333333,
    token0: 'USDC',
    token1: 'CAVE',
    status: 'active',
    version: 3,
    borrowList: ['USDC'],
    isNew: true
  },

  {
    id: '69',
    strategyName: 'GENE-USDC',
    pair: 'GENE-USDC',
    author: 'Francium',
    from: 'Raydium Fusion Pool',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    lpDecimal: 9,
    marketCap: 1333333,
    token0: 'USDC',
    token1: 'GENE',
    status: 'active',
    version: 3,
    borrowList: ['USDC', 'GENE'],
    isNew: true
  },

  {
    id: '70',
    strategyName: 'SONAR-USDC',
    pair: 'SONAR-USDC',
    author: 'Francium',
    from: 'Raydium Fusion Pool',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    lpDecimal: 9,
    marketCap: 1333333,
    token0: 'USDC',
    token1: 'SONAR',
    status: 'active',
    version: 3,
    borrowList: ['USDC'],
    isNew: true
  },

  {
    id: '71',
    strategyName: 'ATLAS-RAY',
    pair: 'ATLAS-RAY',
    author: 'Francium',
    from: 'Raydium Fusion Pool',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    lpDecimal: 8,
    marketCap: 1333333,
    token0: 'RAY',
    token1: 'ATLAS',
    status: 'active',
    version: 3,
    borrowList: ['RAY', 'ATLAS'],
    isNew: true
  },
  {
    id: '72',
    strategyName: 'POLIS-RAY',
    pair: 'POLIS-RAY',
    author: 'Francium',
    from: 'Raydium Fusion Pool',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    lpDecimal: 8,
    marketCap: 1333333,
    token0: 'RAY',
    token1: 'POLIS',
    status: 'active',
    version: 3,
    borrowList: ['RAY', 'POLIS'],
    isNew: true
  },

  {
    id: '73',
    strategyName: 'GENE-RAY',
    pair: 'GENE-RAY',
    author: 'Francium',
    from: 'Raydium Fusion Pool',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    lpDecimal: 9,
    marketCap: 1333333,
    token0: 'RAY',
    token1: 'GENE',
    status: 'active',
    version: 3,
    borrowList: ['RAY', 'GENE'],
    isNew: true
  },
  {
    id: '74',
    strategyName: 'DFL-USDC',
    pair: 'DFL-USDC',
    author: 'Francium',
    from: 'Raydium Fusion Pool',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    lpDecimal: 9,
    marketCap: 1333333,
    token0: 'USDC',
    token1: 'DFL',
    status: 'active',
    version: 3,
    borrowList: ['USDC', 'DFL'],
    isNew: true
  },

  {
    id: '75',
    strategyName: 'SAMO-RAY',
    pair: 'SAMO-RAY',
    author: 'Francium',
    from: 'Raydium Fusion Pool',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    lpDecimal: 9,
    marketCap: 1333333,
    token0: 'RAY',
    token1: 'SAMO',
    status: 'active',
    version: 3,
    borrowList: ['RAY', 'SAMO'],
    isNew: true
  },
  {
    id: '76',
    strategyName: 'LIKE-USDC',
    pair: 'LIKE-USDC',
    author: 'Francium',
    from: 'Raydium Fusion Pool',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    lpDecimal: 9,
    marketCap: 1333333,
    token0: 'USDC',
    token1: 'LIKE',
    status: 'active',
    version: 3,
    borrowList: ['USDC'],
    isNew: true
  },
  {
    id: '77',
    strategyName: 'wbWBNB-USDC',
    pair: 'wbWBNB-USDC',
    author: 'Francium',
    from: 'Raydium Fusion Pool',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    lpDecimal: 8,
    marketCap: 1333333,
    token0: 'USDC',
    token1: 'wbWBNB',
    status: 'active',
    version: 3,
    borrowList: ['USDC', 'wbWBNB'],
    isNew: true
  },

  {
    id: '78',
    strategyName: 'SOL-USDC',
    alias: 'SOL-USDC[Raydium]',
    pair: 'SOL-USDC',
    author: 'Francium',
    from: 'Raydium Fusion Pool',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    lpDecimal: 9,
    marketCap: 1333333,
    token0: 'USDC',
    token1: 'SOL',
    status: 'active',
    version: 3,
    borrowList: ['USDC', 'SOL'],
    isNew: true
  },

  {
    id: '79',
    strategyName: 'SOL-USDT',
    pair: 'SOL-USDT',
    author: 'Francium',
    from: 'Raydium Fusion Pool',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 3,
    minLeverage: 1,
    lpDecimal: 9,
    marketCap: 1333333,
    token0: 'USDT',
    token1: 'SOL',
    status: 'active',
    version: 3,
    borrowList: ['USDT', 'SOL'],
    isNew: true
  },

  {
    id: '80',
    strategyName: 'REAL-USDC',
    pair: 'REAL-USDC',
    author: 'Francium',
    from: 'Raydium Fusion Pool',
    yieldFarmingAPR: 0,
    strategyAPR: 0,
    tradingFeeAPR: 0,
    borrowAPR: 0,
    maxLeverage: 2,
    minLeverage: 1,
    lpDecimal: 9,
    marketCap: 1333333,
    token0: 'USDC',
    token1: 'REAL',
    status: 'active',
    version: 3,
    borrowList: ['USDC'],
    isNew: true
  },
];
