import { PublicKey } from "@solana/web3.js";

export const FRANCIUM_AUTO_VAULTS_PROGRAM_ID = new PublicKey("FVAUXEVi4qwpGCDSvb1wxMSJ6hXWzSPdfZqYXa19hVDz");

export const MarketInfo = {
  MarketInfoAccount: "Ch15dYReFdK7Dewoz6eYAwXZeh9i4kqrKy3VBjsS5JZE",
  owner: "7MBLg6oV5phip11YBbJPuq7u38kdzSi9PM3BifKSpLaR",
  feeReceiver: "7MBLg6oV5phip11YBbJPuq7u38kdzSi9PM3BifKSpLaR",
};

export const LendingInfo = {
  "programId": "FC81tbGt6JWRXidaWYFXxGnTk4VgobhJHATvTRVMqgWj",
  "marketInfoAccount": "4XNif294wbrxj6tJ8K5Rg7SuaEACnu9s2L27i28MQB6E",
  "marketAuthority": "sCDiYj7X7JmXg5fVq2nqED2q1Wqjo7PnqMgH3casMem",
  "marketOwner": "7MBLg6oV5phip11YBbJPuq7u38kdzSi9PM3BifKSpLaR",
};

export const AUTO_RAYDIUM_FARM_CONFIG = {
  // "L4x-SOLUSDC-RAY1": {
  //   pair: 'SOL-USDC',
  //   "tknMint0": "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
  //   "tknMint1": "So11111111111111111111111111111111111111112",
  //   "lpMint": "8HoQnePLqPj4M7PUDzfw8e3Ymdwgc7NLGnaTUapubyvu",
  //   "rewardsMint": "4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R",
  //   "rewardsMintB": "SRMuApVNdxXokk5GT7XD5cUUgXMBCoAz2LHeuAoKWRt",

  //   "poolInfoAccount": "6mEFMM9EzAmCoeG75syF3y9mYc8rCbycU5BS2hppPrDb",
  //   "poolAuthority": "A7yL7NrMWtnvmD5Zaup53pBBPVADDpX3t13PLZiSvcAL",
  //   "poolTknAccount0": "HqRmPF1bbtp7EzypYB9k81UsNoCV63izWrHTMP8wvDG6",
  //   "poolTknAccount1": "G3z5ouUivqwyqLhCoKzhNtjcwEBjnUwkfSKNnADbAnKU",
  //   "poolLpAccount": "9wTPKas9Ke8pvoP57r3zgv3dEcZ8D8d5Pi3iEenXCzYq",
  //   "poolBorrowingCreditTokenAccount0": "J8vwYWBU7ixoZWCqMHrkj1jiSKUVjd9D5eVKUYLbwSHx",
  //   "poolBorrowingCreditTokenAccount1": "2zqzatKmt8Td2sdvqjWVMRK2kJ9kLoGCMbFGfibDp8Gx",
  //   "poolRewardsTokenAccount": "3qSi6kagCi6kA1ppmzVU1EUFVMhsantgsNunV7iDvRno",
  //   "poolRewardsTokenAccountB": "DUPZ8DkGLHQwW8nmvh2uQcK9CEvuZEyjkVcG8bMSWwFG",
  //   "poolFarmInfo": "6J5JjqMeYjxU2yqCas1BVp7ZXUYpvdCzXs11sPhJzDE1",

  //   // lending pool info
  //   "lendingPool0": {
  //     "lendingPoolInfoAccount": "Hx6LbkMHe69DYawhPyVNs8Apa6tyfogfzQV6a7XkwBUU",
  //     "lendingPoolTknAccount": "CFp9kt8z3Epb1QSiEp3xA44KbSwuJxhFR3wQoerFqYS9",
  //     "lendingPoolFeeAccount": "6h6vVc42moDmRs7KahQpFs8YWL5GfWBrxT9UrsUvpApn",
  //     "lendingPoolShareMint": "62fDf5daUJ9jBz8Xtj6Bmw1bh1DvHn8AG4L9hMmxCzpu",
  //     "lendingPoolShareAccount": "Gyc1V1xbA9NjzuURE662ATw6W4AdhwvsL26yUnSGhbkz",
  //     "lendingPoolCreditMint": "CZ2s85dnuAVyGbRWBNauHZwj9oTV2i9xTvFwc1Cedr7E",
  //     "lendingPoolCreditAccount": "Bd71jEvypKFs8N5gByyhD2149tSqLy4PVAzFFShCTJTB",
  //   },
  //   "lendingPool1": {
  //     "lendingPoolInfoAccount": "EnZC8MB6QLTxwN1LNqCXYC7XMpvXqitnYQPf5y5AcQRn",
  //     "lendingPoolTknAccount": "GiJwrxQW5NQWWAva4rnDMXwHxfrhyUzwMX5to1pmCCgF",
  //     "lendingPoolFeeAccount": "wLq5xWzkgfH1T2bbByBoUFxKk5g4K2urQv8q71gCsbM",
  //     "lendingPoolShareMint": "92Zst3rEoJsyZUW2yNc2811GtkBwFrm3tqgxMTtFWuSB",
  //     "lendingPoolShareAccount": "Hyi1jMgc9MMEZyaG9ziL2PvT7zbeRNKhb5K1kj9bxz4x",
  //     "lendingPoolCreditMint": "7x61NrCzeekHwgW5Nk4afMg2sxjMK6RyMkx8tCzzX4qG",
  //     "lendingPoolCreditAccount": "WuPCgCuyLSXatdjyWqkGjCPSQFgKLwcfsNR9fDq3hVL",
  //   },

  //   // amm pool info
  //   "raydiumProgramId": "675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8",
  //   "ammId": "58oQChx4yWmvKdwLLZzBi4ChoCc2fqCUWBkwMihLYQo2",
  //   "ammAuthority": "5Q544fKrFoe6tsEbD7S8EmxGTJYAKtTVhAW5Q5pge4j1",
  //   "ammOpenOrders": "HRk9CMrpq7Jn9sh7mzxE8CChHG8dneX9p475QKz4Fsfc",
  //   "ammTargetOrders": "CZza3Ej4Mc58MnxWA385itCC9jCo3L1D7zc3LKy1bZMR",
  //   "ammCoinAccount": "DQyrAcCrDXQ7NeoqGgDCZwBvWDcYmFCjSb9JtteuvPpz",
  //   "ammPcAccount": "HLmqeL62xR1QoZ1HKKbXRrdN1p3phKpxRMb2VVopvBBz",
  //   "poolWithdrawQueue": "G7xeGGLevkRwB5f44QNgQtrPKBdMfkT6ZZwpS9xcC97n",
  //   "poolTempLpTokenAccount": "Awpt6N7ZYPBa4vG4BQNFhFxDj4sxExAA9rpBAoBw2uok",
  //   "serumProgramId": "9xQeWvG816bUx9EPjHmaT23yvVM2ZWbrrpZb9PusVFin",
  //   "serumMarketId": "9wFFyRfZBsuAha4YcuxcXLKwMxJR43S7fPfQLusDBzvT",
  //   "serumBids": "14ivtgssEBoBjuZJtSAPKYgpUK7DmnSwuPMqJoVTSgKJ",
  //   "serumAsks": "CEQdAFKdycHugujQg9k2wbmxjcpdYZyVLfV9WerTnafJ",
  //   "serumEventQueue": "5KKsLVU6TcbVDK4BS6K1DGDxnh4Q9xjYJ8XaDCG5t8ht",
  //   "serumCoinVault": "36c6YqAwyGKQG66XEp2dJc5JqjaBNv7sVghEtJv4c7u6",
  //   "serumPCVault": "8CFo8bL8mZQK8abbFyypFMwEDd8tVJjHTTojMLgQTUSZ",
  //   "serumVaultSigner": "F8Vyqk3unwxkXukZFQeYyGmFfTG3CAX4v24iyrjEYBJV",
  //   "stakePoolProgramId": "9KEPoZmtHUrBbhWN1v1KWLMkkvwY6WLtAVUCPRtRjP4z",
  //   "stakePoolId": "GUzaohfNuFbBqQTnPgPSNciv3aUvriXYjQduRE3ZkqFw",
  //   "stakePoolAuthority": "DgbCWnbXg43nmeiAveMCkUUPEpAr3rZo3iop3TyP6S63",
  //   "stakePoolLpAccount": "J6ECnRDZEXcxuruvErXDWsPZn9czowKynUr9eDSQ4QeN",
  //   "stakePoolRewardAccount": "38YS2N7VUb856QDsXHS1h8zv5556YgEy9zKbbL2mefjf",
  //   "stakePoolRewardAccountB": "ANDJUfDryy3jY6DngwGRXVyxCJBT5JfojLDXwZYSpnEL",
  //   "ammIdForRewards": "6UmmUiYoBjSrhakAobJw8BvkmJtDVxaeBtbt7rxWo1mg",
  //   "ammIdForRewardsB": "8tzS7SkUZyHPQY7gLqsMCXZ5EDCgjESUHcB17tiR1h3Z",
  // },
  "L4x-stSOLUSDC-RAY1": {
    pair: "stSOL-USDC",
    "tknMint0": "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
    "tknMint1": "7dHbWXmci3dT8UFYWYZweBLXgycu7Y3iL6trKn1Y7ARj",
    "lpMint": "HDUJMwYZkjUZre63xUeDhdCi8c6LgUDiBqxmP3QC3VPX",

    "rewardsMint": "4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R",
    "rewardsMintB": "HZRCwxP2Vq9PCpPXooayhJ2bxTpo5xfpQrwB1svh332p",

    "lookupTableAddress": "sVV72CuHskMu6MJXGSvHipb6MwUL4aaL35r2f4e1qdo",

    "poolInfoAccount": "9MyizhducEsovbQ6rd3jRpYUwH4jx3hJT6hcvcTAtNJf",
    "poolAuthority": "JABdwNh9ZUtzHkwzF6HHdg6DTfKm4sdLePbqR4kNQ5Re",
    "poolTknAccount0": "8C2VCeu57AAy1zHGznsTEe3HiBWJDVXfUQtNpYn7pwPt",
    "poolTknAccount1": "4bt7X1zm1acHSPHsA9xLg1X7m5DWmhYJTGreAYFR373Y",
    "poolLpAccount": "A2VcyobtoPJZbrFvLwFFhwrxw5Uj1LBzu7x8pSUfBaeX",
    "poolBorrowingCreditTokenAccount0": "8ymz24KTSDsM39AJUQyUgsWT6USS4ho4zWq287SvkBYp",
    "poolBorrowingCreditTokenAccount1": "AJCCX5Y9yF9NQHHgHkt1DR6MHm4BWucpkX2j9jirpXJg",
    "poolRewardsTokenAccount": "8UBoZinMJLAuf89ZojxQfb26NjCooAtUaqv42VnnQGmz",
    "poolRewardsTokenAccountB": "D3ZVSmm15MAiXjSoT4parAxJ5XwaV8mUDB5bzzWYPnkX",
    "poolFarmInfo": "DCNdVZEqxniJf88niGpfSDJd7bYSaMrC6wFn9VgFfzii",

    // lending pool info
    "lendingPool0": {
      "lendingPoolInfoAccount": "Hx6LbkMHe69DYawhPyVNs8Apa6tyfogfzQV6a7XkwBUU",
      "lendingPoolTknAccount": "CFp9kt8z3Epb1QSiEp3xA44KbSwuJxhFR3wQoerFqYS9",
      "lendingPoolFeeAccount": "6h6vVc42moDmRs7KahQpFs8YWL5GfWBrxT9UrsUvpApn",
      "lendingPoolShareMint": "62fDf5daUJ9jBz8Xtj6Bmw1bh1DvHn8AG4L9hMmxCzpu",
      "lendingPoolShareAccount": "Gyc1V1xbA9NjzuURE662ATw6W4AdhwvsL26yUnSGhbkz",
      "lendingPoolCreditMint": "CZ2s85dnuAVyGbRWBNauHZwj9oTV2i9xTvFwc1Cedr7E",
      "lendingPoolCreditAccount": "Bd71jEvypKFs8N5gByyhD2149tSqLy4PVAzFFShCTJTB",
    },
    "lendingPool1": {
      "lendingPoolInfoAccount": "9ogtxmnUF94KaPn3dB3unT5yyu7rpzSwc5igysgqFxrU",
      "lendingPoolTknAccount": "85pJTrAVdjHNvgCcUtefwkSe9RDKnHueyvs2uTocWmWs",
      "lendingPoolFeeAccount": "32jTm1CJsUGVSWhp8jMKQSCs4wC8GbZCWK7SkeCGSqYH",
      "lendingPoolShareMint": "HyxfDg47HKS1rQUXWvJH2XQhwEJM3AqrHU7sK9bSNt5h",
      "lendingPoolShareAccount": "3H64RCjRcHEJAJK9mZ3q1mBZJ2hWuv3tUvXVY7XgFL5L",
      "lendingPoolCreditMint": "Hhh5mQQMuWjmyUNyYFDtuXKFp9wptPuLYvH9x98FSDq8",
      "lendingPoolCreditAccount": "CRorEh6T7aXamCsjggckCMgF1ewVavo6CfXTPNkipson",
    },

    // amm pool info
    "raydiumProgramId": "675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8",
    "ammId": "6a1CsrpeZubDjEJE9s1CMVheB6HWM5d7m1cj2jkhyXhj",
    "ammAuthority": "5Q544fKrFoe6tsEbD7S8EmxGTJYAKtTVhAW5Q5pge4j1",
    "ammOpenOrders": "28NQqHxrqMYMQ67aWyn9AzZ1F16PYd4zvLpiiKnEZpsD",
    "ammTargetOrders": "B8nmqinHQjyqAnMWNiqSzs1Jb8VbMpX5k9VUMnDp1gUA",
    "ammCoinAccount": "DD6oh3HRCvMzqHkGeUW3za4pLgWNPJdV6aNYW3gVjXXi",
    "ammPcAccount": "6KR4qkJN91LGko2gdizheri8LMtCwsJrhtsQt6QPwCi5",
    "poolWithdrawQueue": "5i9pTTk9x7r8fx8mJMBCEN85URVLAnkLzZXKyoutUJhU",
    "poolTempLpTokenAccount": "GiuNbiBirwsBp9GuxGYgNUMMKGM6Qf6wqgnxbJFHTYFa",
    "serumProgramId": "9xQeWvG816bUx9EPjHmaT23yvVM2ZWbrrpZb9PusVFin",
    "serumMarketId": "5F7LGsP1LPtaRV7vVKgxwNYX4Vf22xvuzyXjyar7jJqp",
    "serumBids": "HjJSzUbis6VhBZLCbSFN1YtvWLLdxutb7WEvymCLrBJt",
    "serumAsks": "9e37wf6QUqe2s4J6UUNsuv6REQkwTxd47hXhDanm1adp",
    "serumEventQueue": "CQY7LwdZJrfLRZcmEzUYp34XJbxhnxgF4UXmLKqJPLCk",
    "serumCoinVault": "4gqecEySZu6SEgCNhBJm7cEn2TFqCMsMNoiyski5vMTD",
    "serumPCVault": "6FketuhRzyTpevhgjz4fFgd5GL9fHeBeRsq9uJvu8h9m",
    "serumVaultSigner": "x1vRSsrhXkSn7xzJfu9mYP2i19SPqG1gjyj3vUWhim1",
    "stakePoolProgramId": "9KEPoZmtHUrBbhWN1v1KWLMkkvwY6WLtAVUCPRtRjP4z",
    "stakePoolId": "5gzQgxaKAU13SZeffmjjE2y9HwMJ42FxQkqJhJ5nqHeh",
    "stakePoolAuthority": "DKSSeokFtU7cHKMdgNcZ72JETgf9Q3PqcGsk6hnzKxT4",
    "stakePoolLpAccount": "CoUQ1tcRkEyxbCHfLkjxgUtYVhrRbsdeMKT7zB2iCZg5",
    "stakePoolRewardAccount": "5fnav2gjLUjPCwHEnm2vMVmsDV3V8sfjj7MwfeUdgdtM",
    "stakePoolRewardAccountB": "8geEcDpFkXqR2UEE2LVcYCzsD9cyGwJSu8Q56uqr1xs6",
    "ammIdForRewards": "6UmmUiYoBjSrhakAobJw8BvkmJtDVxaeBtbt7rxWo1mg",
    "ammIdForRewardsB": "G4Bjsy5oYVQifvf8pRteX7Lk8YMe9EKf6BRhwGiCK76B",
    "ammForRewards": {
      "swapDirection": 0,
      "ammId": "6UmmUiYoBjSrhakAobJw8BvkmJtDVxaeBtbt7rxWo1mg",
      "ammAuthority": "5Q544fKrFoe6tsEbD7S8EmxGTJYAKtTVhAW5Q5pge4j1",
      "ammOpenOrders": "J8u8nTHYtvudyqwLrXZboziN95LpaHFHpd97Jm5vtbkW",
      "ammTargetOrders": "3cji8XW5uhtsA757vELVFAeJpskyHwbnTSceMFY5GjVT",

      "ammCoinAccount": "FdmKUE4UMiJYFK5ogCngHzShuVKrFXBamPWcewDr31th",
      "ammPcAccount": "Eqrhxd7bDUCH3MepKmdVkgwazXRzY6iHhEoBpY7yAohk",
      "poolWithdrawQueue": "ERiPLHrxvjsoMuaWDWSTLdCMzRkQSo8SkLBLYEmSokyr",
      "poolTempLpTokenAccount": "D1V5GMf3N26owUFcbz2qR5N4G81qPKQvS2Vc4SM73XGB",
      "serumProgramId": "9xQeWvG816bUx9EPjHmaT23yvVM2ZWbrrpZb9PusVFin",
      "serumMarketId": "2xiv8A5xrJ7RnGdxXB42uFEkYHJjszEhaJyKKt4WaLep",
      "serumBids": "Hf84mYadE1VqSvVWAvCWc9wqLXak4RwXiPb4A91EAUn5",
      "serumAsks": "DC1HsWWRCXVg3wk2NndS5LTbce3axwUwUZH1RgnV4oDN",
      "serumEventQueue": "H9dZt8kvz1Fe5FyRisb77KcYTaN8LEbuVAfJSnAaEABz",
      "serumCoinVault": "GGcdamvNDYFhAXr93DWyJ8QmwawUHLCyRqWL3KngtLRa",
      "serumPCVault": "22jHt5WmosAykp3LPGSAKgY45p7VGh4DFWSwp21SWBVe",
      "serumVaultSigner": "FmhXe9uG6zun49p222xt3nG1rBAkWvzVz7dxERQ6ouGw",
    },
    "ammForRewardsB": {
      "swapDirection": 3,
      "ammId": "G4Bjsy5oYVQifvf8pRteX7Lk8YMe9EKf6BRhwGiCK76B",
      "ammAuthority": "5Q544fKrFoe6tsEbD7S8EmxGTJYAKtTVhAW5Q5pge4j1",
      "ammOpenOrders": "Hukwk3eX2L2rDmaThLz6ihiowtnzCNs3Uerxe41ZBe4A",
      "ammTargetOrders": "2Ug2MkExgGmUa9CqMVGEucz1XYmizitXp5r4pJRoebyx",

      "ammCoinAccount": "3XcFG7j5YymVHJ2ntEvbKgY3hTfY4nazSKNYQmUkJDVJ",
      "ammPcAccount": "HdXRvcchDKhQ4eevXD13gzygt45AmRDhy2rHBGVnDd6v",
      "poolWithdrawQueue": "ACHw7iohzzmZXKMM2gvAm5E5vZwhwUNBbPsrT4NH4uDz",
      "poolTempLpTokenAccount": "BV9yKVyfp3YxLR5ec63LvBzWsDqt8N5ScS994UNUE5LE",
      "serumProgramId": "9xQeWvG816bUx9EPjHmaT23yvVM2ZWbrrpZb9PusVFin",
      "serumMarketId": "DZWSgCDNK2KhHKctAHG7AtUpsUPH6JtMwCsd6jHBJXib",
      "serumBids": "8rxjMvFyfwF1softN4rB66EFN8EPXQtskUBZ9UjuPd4E",
      "serumAsks": "J25z39PaC7eE1SRRv3goQWvF9qvZuxvv4eFeiiYAnJPp",
      "serumEventQueue": "HDjFYPWpgqLcSbtBJ4q4y9Gazpn8R1PU89UbZZezbchu",
      "serumCoinVault": "CqNXBsZkFxXhwjnJGdREsTAV3TgoqdghyW3iYwzMDJAh",
      "serumPCVault": "9N6K9DTMvbF9mkHFqWTQ9y3XnqRrSEZn15QYibKHiS6i",
      "serumVaultSigner": "3T2NeZ5TapimEWXC4Vx6hQXduBeH3myCoxZhnG7ZQpJ3"
    }
  },
  "L4x-stSOLUSDT-RAY1": {
    pair: "stSOL-USDT",
    "tknMint0": "Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB",
    "tknMint1": "7dHbWXmci3dT8UFYWYZweBLXgycu7Y3iL6trKn1Y7ARj",
    "lpMint": "2pdg9vAH8GsTTWSSP3Za6j5ts4Nzs6tEbNterVe9H62H",
    "rewardsMint": "4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R",
    "rewardsMintB": "HZRCwxP2Vq9PCpPXooayhJ2bxTpo5xfpQrwB1svh332p",

    "lookupTableAddress": "zWUCdkaXnqpX6nCf2MXRhGHDKsEa2oVPANdRykHPD7H",

    "poolInfoAccount": "5xiisEHC6wdCUT9UmHn3uTFomw2M2zFEf5MzC7z8epmM",
    "poolAuthority": "GV4BRad5z3pyLQni6ZWNGrvE6P1J9cN9qW9S3ya1zaHN",
    "poolTknAccount0": "7hmiJCTHRAN46mfyNKiJQsKumNZb3qPoinXcJH8mpPvE",
    "poolTknAccount1": "D4JpwWVY3pmj1nZLV2paJA6xRVGrPg9Q9qt6WQX32WLd",
    "poolLpAccount": "6UowivTUWh1srJ1D63oqAXVe9z7ND8GvEfoMxEQLHqn4",
    "poolBorrowingCreditTokenAccount0": "4QB1AKSRTjC2P89mHLzQmRp4q25HyHt4YjU7C5dykJAx",
    "poolBorrowingCreditTokenAccount1": "3RNLjXR38puiwj3LUwTi2Kf51FPqMKE5Qcc3GjwXbaYY",
    "poolRewardsTokenAccount": "5N86hKxYdaTSCcwtzVr3mHygF9u4qrdT8mw6VEi1jBQG",
    "poolRewardsTokenAccountB": "38BPe2mYYQJHeipMYFuqMibjKLZb8ek8suQC1fdcz9Bu",
    "poolFarmInfo": "FithwmUbUXaDRUqnaSMi1dp8EkTvUQbRnPsQfn96cKp1",

    // lending pool info
    "lendingPool0": {
      "lendingPoolInfoAccount": "EyqWUeme2B1dhuwJvJVi2coYPcGWmWrakcpsSFeikrhb",
      "lendingPoolTknAccount": "Acx3Ky9pk8CyYftA9HYF31EbVhBDi21EqJsFtMW2XxXW",
      "lendingPoolFeeAccount": "8f92LjiwrtVZHmL3TW1vbg3pG2C3B7LLQ9hRS4j13caX",
      "lendingPoolShareMint": "8TtsTZQ6mU4YSW5jw4sDjSDEG1CW8QLpK7C9g5TVgBvn",
      "lendingPoolShareAccount": "EfLgyXRGFi9MUCMgrsFBuAJ7pMPXBceKhD6x4PgdvLLc",
      "lendingPoolCreditMint": "CoheXVD8cAdVaKznfay22dBpfML5Fbz5g4j67syKgRg4",
      "lendingPoolCreditAccount": "EAQxDXsA6RXxWtA1PwZNnTnj2MapHBtMzvUmfuGPJCPX",
    },
    "lendingPool1": {
      "lendingPoolInfoAccount": "9ogtxmnUF94KaPn3dB3unT5yyu7rpzSwc5igysgqFxrU",
      "lendingPoolTknAccount": "85pJTrAVdjHNvgCcUtefwkSe9RDKnHueyvs2uTocWmWs",
      "lendingPoolFeeAccount": "32jTm1CJsUGVSWhp8jMKQSCs4wC8GbZCWK7SkeCGSqYH",
      "lendingPoolShareMint": "HyxfDg47HKS1rQUXWvJH2XQhwEJM3AqrHU7sK9bSNt5h",
      "lendingPoolShareAccount": "3H64RCjRcHEJAJK9mZ3q1mBZJ2hWuv3tUvXVY7XgFL5L",
      "lendingPoolCreditMint": "Hhh5mQQMuWjmyUNyYFDtuXKFp9wptPuLYvH9x98FSDq8",
      "lendingPoolCreditAccount": "CRorEh6T7aXamCsjggckCMgF1ewVavo6CfXTPNkipson",
    },

    // amm pool info
    "raydiumProgramId": "675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8",
    "ammId": "9euZD3C1d7e2fLKnUxHc7oUUDJcYnguMT6cRzLY9y4o7",
    "ammAuthority": "5Q544fKrFoe6tsEbD7S8EmxGTJYAKtTVhAW5Q5pge4j1",
    "ammOpenOrders": "26YmKFtedce9kycdjo23DFA9XcMqJCjsqUTywzh5Qh52",
    "ammTargetOrders": "JYyNiaTpvS7Tq5egRS7Qeq4Xaes1qwe9fd5tXi7Rsu2",
    "ammCoinAccount": "Hn7pZvyfMJ6c6h2TD2GAk6YXf1QZAeprSz9v7Qt97DWg",
    "ammPcAccount": "6kZ4zcNxPzKAt33Hiq1GKPrSmdw1M28mzyKKmwHWUqPJ",
    "poolWithdrawQueue": "5FozwM7mGKvshoGy9CpVNTGnynRu2gVydiQczYRfLnHS",
    "poolTempLpTokenAccount": "EhNGjPxTyGTwC7NmyRpqop5hAGWzQX56UpX2nmAUFCUh",
    "serumProgramId": "9xQeWvG816bUx9EPjHmaT23yvVM2ZWbrrpZb9PusVFin",
    "serumMarketId": "FDkK55eE6Ro9mURo4YGgHafL3D5NW8yhnkUAFFoJB8SD",
    "serumBids": "pPHrhPTCLhxn6HGaPji6NC9mQux5NveFMuqucjr4gw8",
    "serumAsks": "4kEEvo4Rh3AdqtDjrcKXYtryctjt3Y9yrdgQix6e2MTB",
    "serumEventQueue": "2RtogEw3wXbmTnVKmxtWVB7fGZPbsbgShxeGgV1n1znH",
    "serumCoinVault": "BcySyd2CYFmVAm4qjWRPAQhpzjBYdKL44tQy81BieEUW",
    "serumPCVault": "4ZMS58ocMSiJWoNBMrh2g2U1vS6EM6cMAoVMhkqbg717",
    "serumVaultSigner": "GXZhuCYFVauwV4R9zxr7CuhNUo6bFLFcsMM233k9pdef",
    "stakePoolProgramId": "9KEPoZmtHUrBbhWN1v1KWLMkkvwY6WLtAVUCPRtRjP4z",
    "stakePoolId": "BoB7TtQ6fgVceh1JMtwgL1CqfC9hKWDHfQ3QPsM7d17M",
    "stakePoolAuthority": "Dw6aduBVBxp425wfSWdPFD1N17PZgsDABbeD5LNVQBDa",
    "stakePoolLpAccount": "G9E9XKrDTHRHcX68uGxSCkY54NYtQ1D9rJSFePGySPMC",
    "stakePoolRewardAccount": "BunXUabRBaYi8t9bE4KLcaVWwxZpN8gbVu1irxfCvyQg",
    "stakePoolRewardAccountB": "2WQpLs1rmqqaRUZjKpvALev1VaytsmuPsixkNTe42jey",
    "ammIdForRewards": "6UmmUiYoBjSrhakAobJw8BvkmJtDVxaeBtbt7rxWo1mg",
    "ammIdForRewardsB": "G4Bjsy5oYVQifvf8pRteX7Lk8YMe9EKf6BRhwGiCK76B",
    "ammForRewards": {
      "swapDirection": 0,
      "ammId": "6UmmUiYoBjSrhakAobJw8BvkmJtDVxaeBtbt7rxWo1mg",
      "ammAuthority": "5Q544fKrFoe6tsEbD7S8EmxGTJYAKtTVhAW5Q5pge4j1",
      "ammOpenOrders": "J8u8nTHYtvudyqwLrXZboziN95LpaHFHpd97Jm5vtbkW",
      "ammTargetOrders": "3cji8XW5uhtsA757vELVFAeJpskyHwbnTSceMFY5GjVT",

      "ammCoinAccount": "FdmKUE4UMiJYFK5ogCngHzShuVKrFXBamPWcewDr31th",
      "ammPcAccount": "Eqrhxd7bDUCH3MepKmdVkgwazXRzY6iHhEoBpY7yAohk",
      "poolWithdrawQueue": "ERiPLHrxvjsoMuaWDWSTLdCMzRkQSo8SkLBLYEmSokyr",
      "poolTempLpTokenAccount": "D1V5GMf3N26owUFcbz2qR5N4G81qPKQvS2Vc4SM73XGB",
      "serumProgramId": "9xQeWvG816bUx9EPjHmaT23yvVM2ZWbrrpZb9PusVFin",
      "serumMarketId": "2xiv8A5xrJ7RnGdxXB42uFEkYHJjszEhaJyKKt4WaLep",
      "serumBids": "Hf84mYadE1VqSvVWAvCWc9wqLXak4RwXiPb4A91EAUn5",
      "serumAsks": "DC1HsWWRCXVg3wk2NndS5LTbce3axwUwUZH1RgnV4oDN",
      "serumEventQueue": "H9dZt8kvz1Fe5FyRisb77KcYTaN8LEbuVAfJSnAaEABz",
      "serumCoinVault": "GGcdamvNDYFhAXr93DWyJ8QmwawUHLCyRqWL3KngtLRa",
      "serumPCVault": "22jHt5WmosAykp3LPGSAKgY45p7VGh4DFWSwp21SWBVe",
      "serumVaultSigner": "FmhXe9uG6zun49p222xt3nG1rBAkWvzVz7dxERQ6ouGw",
    },
    "ammForRewardsB": {
      "swapDirection": 3,
      "ammId": "G4Bjsy5oYVQifvf8pRteX7Lk8YMe9EKf6BRhwGiCK76B",
      "ammAuthority": "5Q544fKrFoe6tsEbD7S8EmxGTJYAKtTVhAW5Q5pge4j1",
      "ammOpenOrders": "Hukwk3eX2L2rDmaThLz6ihiowtnzCNs3Uerxe41ZBe4A",
      "ammTargetOrders": "2Ug2MkExgGmUa9CqMVGEucz1XYmizitXp5r4pJRoebyx",

      "ammCoinAccount": "3XcFG7j5YymVHJ2ntEvbKgY3hTfY4nazSKNYQmUkJDVJ",
      "ammPcAccount": "HdXRvcchDKhQ4eevXD13gzygt45AmRDhy2rHBGVnDd6v",
      "poolWithdrawQueue": "ACHw7iohzzmZXKMM2gvAm5E5vZwhwUNBbPsrT4NH4uDz",
      "poolTempLpTokenAccount": "BV9yKVyfp3YxLR5ec63LvBzWsDqt8N5ScS994UNUE5LE",
      "serumProgramId": "9xQeWvG816bUx9EPjHmaT23yvVM2ZWbrrpZb9PusVFin",
      "serumMarketId": "DZWSgCDNK2KhHKctAHG7AtUpsUPH6JtMwCsd6jHBJXib",
      "serumBids": "8rxjMvFyfwF1softN4rB66EFN8EPXQtskUBZ9UjuPd4E",
      "serumAsks": "J25z39PaC7eE1SRRv3goQWvF9qvZuxvv4eFeiiYAnJPp",
      "serumEventQueue": "HDjFYPWpgqLcSbtBJ4q4y9Gazpn8R1PU89UbZZezbchu",
      "serumCoinVault": "CqNXBsZkFxXhwjnJGdREsTAV3TgoqdghyW3iYwzMDJAh",
      "serumPCVault": "9N6K9DTMvbF9mkHFqWTQ9y3XnqRrSEZn15QYibKHiS6i",
      "serumVaultSigner": "3T2NeZ5TapimEWXC4Vx6hQXduBeH3myCoxZhnG7ZQpJ3"
    }
  }
};

export const AUTO_RAYDIUM_EXTRA_CONFIG = {
  // "L4x-SOLUSDC-RAY1": {
  //   priceKey: 'SOL-USDC[Raydium]',
  //   lpDecimals: 9,
  //   leverage: 4,
  //   rebalanceType: 'delta',
  //   threshold: 4
  // },
  "L4x-stSOLUSDC-RAY1": {
    priceKey: 'stSOL-USDC[Raydium]',
    lpDecimals: 9,
    leverage: 4,
    rebalanceType: 'delta',
    threshold: 4
  },
  "L4x-stSOLUSDT-RAY1": {
    priceKey: 'stSOL-USDT[Raydium]',
    lpDecimals: 9,
    leverage: 4,
    rebalanceType: 'delta',
    threshold: 4
  }
};
