import { PublicKey } from "@solana/web3.js";
import { LIQUIDITY_POOL_PROGRAM_ID_V4, SERUM_PROGRAM_ID_V3, STAKE_PROGRAM_ID_V5 } from "./info";

const franciumProgramId = new PublicKey('7JTZCgcKVJaGRZkauZ8nRuPc8qEs8zcnsrrDfvpz4Yp');

export const legacyInfoList = {
  'MEDIA-USDC': {
    strategyAccount: new PublicKey('EKrHQ4HWiJ2Uh2JKWtBVJdu9DXnbMHm5Y7XddGutt9gA'),
    strategyAuthority: new PublicKey('9P64g4ye7kj6YUvr2o19G7dajWM7VJmR81Rx5o7MnCTG'),
    strategyTknAccount: new PublicKey('7qu9jjrcFDawArQCnVkPFgTQadnjuFWk2h3wLku1kE1C'),
    strategyUsdcAccount: new PublicKey('BA6RnwA7oLnrieDxY2jN2d8bzbvj16aSUei7k9MQpL2C'),
    strategyRayAccount: new PublicKey('XhtRoKtDBeZpmWwQbGx7kxVjsdSikrfNnSLn1KcBz2T'),
    strategyLpAccount: new PublicKey('2yP91rxy7NUdUMMMd56ZvxvTNPsGKAL3YpfL8BzqKuNQ'),
    strategyFarmInfoAccount: new PublicKey('5Be3YSV98CJ3XsMNDaoimcQ7oATDV3C2PhaoPdn8cEZK'),
    strategyBorrowCreditAccount: new PublicKey('Bg13RgKSeao8QBeQvYv4DwZeLu8jDmnMmJPpgdNvgRM'),
    programId: franciumProgramId,
    token1Mint: new PublicKey("EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"), // usdc
    token2Mint: new PublicKey("ETAtLmCmsoiEEKfNrHKJ2kYy3MoABhU6NQvpSfij5tDs"),
    lpMint: new PublicKey("A5zanvgtioZGiJMdEyaKN4XQmJsp1p7uVxaq2696REvQ"),
    raydiumInfo: {
      raydiumProgramId: LIQUIDITY_POOL_PROGRAM_ID_V4,
      ammId: new PublicKey('94CQopiGxxUXf2avyMZhAFaBdNatd62ttYGoTVQBRGdi'),
      ammAuthority: new PublicKey('5Q544fKrFoe6tsEbD7S8EmxGTJYAKtTVhAW5Q5pge4j1'),
      ammOpenOrders: new PublicKey('EdS5vqjihxRbRujPkqqzHYwBqcTP9QPbrBc9CDtnBDwo'),
      ammTargetOrders: new PublicKey('6Rfew8qvNp97PVN14C9Wg8ybqRdF9HUEUhuqqZBWcAUW'),
      lpMintAccount: new PublicKey("A5zanvgtioZGiJMdEyaKN4XQmJsp1p7uVxaq2696REvQ"),
      lpDecimals: 6,
      ammTknAccount: new PublicKey('7zfTWDFmMi3Tzbbd3FZ2vZDdBm1w7whiZq1DrCxAHwMj'),
      ammUsdcAccount: new PublicKey('FWUnfg1hHuanU8LxJv31TAfEWSvuWWffeMmHpcZ9BYVr'),
      poolWithdrawQueue: new PublicKey('F7MUnGrShtQqSvi9DoWyBNRo7FUpRiYPsS9aw77auhiS'),
      poolTempLpTokenAccount: new PublicKey('7oX2VcPYwEV6EUUyMUoTKVVxAPAvGQZcGiGzotX43wNM'),
      serumProgramId: SERUM_PROGRAM_ID_V3,
      serumMarketId: new PublicKey('FfiqqvJcVL7oCCu8WQUMHLUC2dnHQPAPjTdSzsERFWjb'),
      serumBids: new PublicKey('GmqbTDL5QSAhWL7UsE8MriTHSnodWM1HyGR8Cn8GzZV5'),
      serumAsks: new PublicKey('CrTBp7ThkRRYJBL4tprke2VbKYj2wSxJp3Q1LDoHcQwP'),
      serumEventQueue: new PublicKey('HomZxFZNGmH2XedBavMsrXgLnWFpMLT95QV8nCYtKszd'),
      serumTknVault: new PublicKey('D8ToFvpVWmNnfJzjHuumRJ4eoJc39hsWWcLtFZQpzQTt'),
      serumUsdcVault: new PublicKey('6RSpnBYaegSKisXaJxeP36mkdVPe9SP3p2kDERz8Ahhi'),
      serumVaultSigner: new PublicKey('Cz2m3hW2Vcb8oEFz12uoWcdq8mKb9D1N7RTyXpigoFXU'),
      stakePoolProgramId: STAKE_PROGRAM_ID_V5,
      stakePoolId: new PublicKey('Ef1gD9JMzWF6PNw2uc4744zouh57GyWAeVTjHHbQ2nsu'),
      stakePoolAuthority: new PublicKey('3dhU2g3MSHK3LwjuE1VsEJCsNeWKyBJUMHt4EUXepTjs'),
      stakePoolLpAccount: new PublicKey('DGjRtqsjeubLCLPD3yH8fj1d7TnrD3jKBpwa1UbVk7E6'),
      stakePoolRewardAccount: new PublicKey('Uen8f9Rn42i8sDTK5vEttrnX9AUwXV3yf6DFU63mKDb'),
      stakePoolRewardAccountB: new PublicKey('Ek6n7Myojb6pSpQuqk5AyS7KXQdXkJyZT7ki9baYCxds')
    }
  },
  'COPE-USDC': {
    strategyAccount: new PublicKey('GzDvdja7FRxJG5mqy4DjXDDLYkJLDERjmVdjdQadb3Sk'),
    strategyAuthority: new PublicKey('4zoQxpq87khmgmPB9PgbkV7yWdAEo947D8HNwKLyZyvg'),
    strategyTknAccount: new PublicKey('7CJi7FkELdsgzr4iEMn8TNADJ4Toz1DTdQRtCMdxQ2kW'),
    strategyUsdcAccount: new PublicKey('6dFJBka1jKVaUJLaaAFQvhRj5y9by3UcRR2nDEvbi3PF'),
    strategyRayAccount: new PublicKey('CHsKCgLfXppkWdswdwjRAM43T1Y5L21QMGCdFp8Cx65E'),
    strategyLpAccount: new PublicKey('AGxd4gqmC5kCgUu6QDpp8HFiwFvybN8i2Q9sxba4KgUc'),
    strategyFarmInfoAccount: new PublicKey('DEXsSfHbJUTc1tEv5GNnoBPzpXjTqTcLQnGPm1bpkPCG'),
    strategyBorrowCreditAccount: new PublicKey('PNz6JED2fdxBgyp3ewtprkG3myz9RvdCKn2jgA1dRVA'),
    programId: franciumProgramId,
    token1Mint: new PublicKey("EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"), // usdc
    token2Mint: new PublicKey("8HGyAAB1yoM1ttS7pXjHMa3dukTFGQggnFFH3hJZgzQh"),
    lpMint: new PublicKey("Cz1kUvHw98imKkrqqu95GQB9h1frY8RikxPojMwWKGXf"),
    raydiumInfo: {
      raydiumProgramId: LIQUIDITY_POOL_PROGRAM_ID_V4,
      ammId: new PublicKey('DiWxV1SPXPNJRCt5Ao1mJRAxjw97hJVyj8qGzZwFbAFb'),
      ammAuthority: new PublicKey('5Q544fKrFoe6tsEbD7S8EmxGTJYAKtTVhAW5Q5pge4j1'),
      ammOpenOrders: new PublicKey('jg8ayFZLH2cEUJULUirWy7wNggN1eyRnTMt6EjbJUun'),
      ammTargetOrders: new PublicKey('8pE4fzFzRT6aje7B3hYHXrZakeEqNF2kFmJtxkrxUK9b'),
      lpMintAccount: new PublicKey("Cz1kUvHw98imKkrqqu95GQB9h1frY8RikxPojMwWKGXf"),
      lpDecimals: 6,
      ammTknAccount: new PublicKey('FhjBg8vpVgsiW9oCUxujqoWWSPSRvnWNXucEF1G1F39Z'),
      ammUsdcAccount: new PublicKey('Dv95skm7AUr33x1p2Bu5EgvE3usB1TxgZoxjBe2rpfm6'),
      poolWithdrawQueue: new PublicKey('4An6jy1JocXGUjayXqVTx1jvs79o8LgsRk3VvmRgXxaq'),
      poolTempLpTokenAccount: new PublicKey('57hiWKd47VHVD7y8BenqnakSdgQNBvyUrkSpf9BDP6UQ'),
      serumProgramId: SERUM_PROGRAM_ID_V3,
      serumMarketId: new PublicKey('6fc7v3PmjZG9Lk2XTot6BywGyYLkBQuzuFKd4FpCsPxk'),
      serumBids: new PublicKey('FLjCjU5wLUsqF6FeYJaH5JtTTFSTZzTCingxN1uyr9zn'),
      serumAsks: new PublicKey('7TcstD7AdWqjuFoRVK24zFv66v1qyMYDNDT1V5RNWKRz'),
      serumEventQueue: new PublicKey('2dQ1Spgc7rGSuE1t3Fb9RL7zvGc7F7pH9XwJ46u3QiJr'),
      serumTknVault: new PublicKey('2ShBow4Bof4dkLjx8VTRjLXXvUydiBNF7bHzDaxPjpKq'),
      serumUsdcVault: new PublicKey('EFdqJhawpCReiK2DcrbbUUWWc6cd8mqgZm5MSbQ3TR33'),
      serumVaultSigner: new PublicKey('A6q5h5Wx9iqeoVsvYWA7xofUcKx6XUPPab8BTVrW91Bs'),
      stakePoolProgramId: STAKE_PROGRAM_ID_V5,
      stakePoolId: new PublicKey('AxVvbT9fDFEkmdLwKUJRY5HsG2RXAZbe1dRAgJ2bDDwg'),
      stakePoolAuthority: new PublicKey('3n1Vdmqu1MBUpBYMpYbpJAVFv4MeNMEa82waruLy7BDu'),
      stakePoolLpAccount: new PublicKey('BHLzrd5MgQy4NgmUsn542yXRZWkz1iV5bfWg8s8D4tVL'),
      stakePoolRewardAccount: new PublicKey('7nGY6xHCUR2MxJnHT1qvArRUEnpo2DsGGf6Pdu3tt9gv'),
      stakePoolRewardAccountB: new PublicKey('6ezx1EivkxsJcZLYhSJFLc3nUs25iyubf8PPyRNEX3pL')
    }
  },
  'MER-USDC': {
    strategyAccount: new PublicKey('6xW5CcUS3r8F8kBYdnkRY3MGUqwGNAHYBFBNm4C7G83c'),
    strategyAuthority: new PublicKey('ExeydjMJ3udxHfbdZMaZxSJ8uQzmv3hDmLhpbPjGEc3j'),
    strategyTknAccount: new PublicKey('Epkvv4bYtLYsseBytjCTdDrM3bpuqR9J1qA2SEWh6qvB'),
    strategyUsdcAccount: new PublicKey('4FtKnPc4C8Z4DRhQaBsWtQkMtLLurpduXWYMLsBo5xaZ'),
    strategyRayAccount: new PublicKey('6FSRNMavoC9rqzxXBAsXKCanybdYjpitf9mNotfYJEvM'),
    strategyLpAccount: new PublicKey('DFds2HyMAE97j4iYNJ65KvrqARk5fnfgya9rgGxDpG7T'),
    strategyFarmInfoAccount: new PublicKey('bA2yAh7NSxkrSf98qd5pURyLdiu1o7NdotYkswuGnL9'),
    strategyBorrowCreditAccount: new PublicKey('9qTHWYPuLBqfn9jNUAiXD7s3D647f63APsecJsfunncQ'),
    programId: franciumProgramId,
    token1Mint: new PublicKey("EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"), // usdc
    token2Mint: new PublicKey("MERt85fc5boKw3BW1eYdxonEuJNvXbiMbs6hvheau5K"),
    lpMint: new PublicKey("3H9NxvaZoxMZZDZcbBDdWMKbrfNj7PCF5sbRwDr7SdDW"),
    raydiumInfo: {
      raydiumProgramId: LIQUIDITY_POOL_PROGRAM_ID_V4,
      ammId: new PublicKey('BkfGDk676QFtTiGxn7TtEpHayJZRr6LgNk9uTV2MH4bR'),
      ammAuthority: new PublicKey('5Q544fKrFoe6tsEbD7S8EmxGTJYAKtTVhAW5Q5pge4j1'),
      ammOpenOrders: new PublicKey('FNwXaqyYNKNwJ8Qc39VGzuGnPcNTCVKExrgUKTLCcSzU'),
      ammTargetOrders: new PublicKey('DKgXbNmsm1uCJ2eyh6xcnTe1G6YUav8RgzaxrbkG4xxe'),
      lpMintAccount: new PublicKey("3H9NxvaZoxMZZDZcbBDdWMKbrfNj7PCF5sbRwDr7SdDW"),
      lpDecimals: 6,
      ammTknAccount: new PublicKey('6XZ1hoJQZARtyA17mXkfnKSHWK2RvocC3UDNsY7f4Lf6'),
      ammUsdcAccount: new PublicKey('F4opwQUoVhVRaf3CpMuCPpWNcB9k3AXvMMsfQh52pa66'),
      poolWithdrawQueue: new PublicKey('8mqpqWGL7W2xh8B1s6XDZJsmPuo5zRedcM5sF55hhEKo'),
      poolTempLpTokenAccount: new PublicKey('9ex6kCZsLR4ZbMCN4TcCuFzkw8YhiC9sdsJPavsrqCws'),
      serumProgramId: SERUM_PROGRAM_ID_V3,
      serumMarketId: new PublicKey('G4LcexdCzzJUKZfqyVDQFzpkjhB1JoCNL8Kooxi9nJz5'),
      serumBids: new PublicKey('DVjhW8nLFWrpRwzaEi1fgJHJ5heMKddssrqE3AsGMCHp'),
      serumAsks: new PublicKey('CY2gjuWxUFGcgeCy3UiureS3kmjgDSRF59AQH6TENtfC'),
      serumEventQueue: new PublicKey('8w4n3fcajhgN8TF74j42ehWvbVJnck5cewpjwhRQpyyc'),
      serumTknVault: new PublicKey('4ctYuY4ZvCVRvF22QDw8LzUis9yrnupoLQNXxmZy1BGm'),
      serumUsdcVault: new PublicKey('DovDds7NEzFn493DJ2yKBRgqsYgDXg6z38pUGXe1AAWQ'),
      serumVaultSigner: new PublicKey('BUDJ4F1ZknbZiwHb6xHEsH6o1LuW394DE8wKT8CoAYNF'),
      stakePoolProgramId: STAKE_PROGRAM_ID_V5,
      stakePoolId: new PublicKey('D4pYuD4tbir9KBsb7Kr63v9e86JY2UoUZeFK9eHKQFZM'),
      stakePoolAuthority: new PublicKey('2T46saTyTYeEFWyesRzLWj6y1ha9ngwcyWyGNn9q4zu4'),
      stakePoolLpAccount: new PublicKey('EV3wsqiMiNcBmo2mFkUuCtib36NpBCsC2vfkW3By1sSu'),
      stakePoolRewardAccount: new PublicKey('5gEH5Uq2QrqiEhdZ8YFAMY1HoYnKMiuu71f6BC25UXee'),
      stakePoolRewardAccountB: new PublicKey('FTP4hnN5GPtPYvkrscTkKWYVVQ56hV3f4wGgpEXgrDUD')
    }
  },
  'ALEPH-USDC': {
    strategyAccount: new PublicKey('79A2HGgdhuFe6RMFo6HxUwncMBM2dU6sbYdhT2pCCbDm'),
    strategyAuthority: new PublicKey('FnmK2mvskaMzzHWUMEiAm6r1WGsW34xFphf5Xv9J115B'),
    strategyTknAccount: new PublicKey('4j9qafTkTzwmwrAogeKwLNQ5hKXFavb4j7JW17wUiw8K'),
    strategyUsdcAccount: new PublicKey('VmCH9rF64rCGyDG9eT3e4SmG5PeLdtxn9EE7RZ5FGtf'),
    strategyRayAccount: new PublicKey('FUxHH7WLjZF1RtFzd2JhzBM6TKHiNcxyNMgTYLYXZwNF'),
    strategyLpAccount: new PublicKey('7rWb6ghCfMrZoSxLCzwDZzXKCntmX3fF3Gv4HKwNqsTi'),
    strategyFarmInfoAccount: new PublicKey('GkLr55kgm6AWBsRBwuW7frKojQViM6JWo63g48YwTCsh'),
    strategyBorrowCreditAccount: new PublicKey('FZeZgWBJvJgcZERW5BrUyVTdcAunGpkBKc1TCgSXQiib'),
    programId: franciumProgramId,
    token1Mint: new PublicKey("EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"), // usdc
    token2Mint: new PublicKey("CsZ5LZkDS7h9TDKjrbL7VAwQZ9nsRu8vJLhRYfmGaN8K"),
    lpMint: new PublicKey("iUDasAP2nXm5wvTukAHEKSdSXn8vQkRtaiShs9ceGB7"),
    raydiumInfo: {
      raydiumProgramId: LIQUIDITY_POOL_PROGRAM_ID_V4,
      ammId: new PublicKey('GDHXjn9wF2zxW35DBkCegWQdoTfFBC9LXt7D5ovJxQ5B'),
      ammAuthority: new PublicKey('5Q544fKrFoe6tsEbD7S8EmxGTJYAKtTVhAW5Q5pge4j1'),
      ammOpenOrders: new PublicKey('AtUeUK7MZayoDktjrRSJAFsyPiPwPsbAeTsunM5pSnnK'),
      ammTargetOrders: new PublicKey('FMYSGYEL1CPYz8cpgAor5jV2HqeEQRDLMEggoz6wAiFV'),
      lpMintAccount: new PublicKey("iUDasAP2nXm5wvTukAHEKSdSXn8vQkRtaiShs9ceGB7"),
      lpDecimals: 6,
      ammTknAccount: new PublicKey('BT3QMKHrha4fhqpisnYKaPDsv42XeHU2Aovhdu5Bazru'),
      ammUsdcAccount: new PublicKey('9L4tXPyuwuLhmtmX4yaRTK6TB7tYFNHupeENoCdPceq'),
      poolWithdrawQueue: new PublicKey('4nRbmEUp7DQroG71jXv6cJjrhnh91ePdPhzmBSjinwB8'),
      poolTempLpTokenAccount: new PublicKey('9JdpGvmo6aPZYf4hkiZNUjceXgd2RtR1fJgvjuoAuhsM'),
      serumProgramId: SERUM_PROGRAM_ID_V3,
      serumMarketId: new PublicKey('GcoKtAmTy5QyuijXSmJKBtFdt99e6Buza18Js7j9AJ6e'),
      serumBids: new PublicKey('HmpcmzzajDvhFSXb4pmJo5mb23zW8Cj9FEeB3hVT78jV'),
      serumAsks: new PublicKey('8sfGm6jsFTAcb4oLuqMKr1xNEBd5CXuNPAKZEdbeezA'),
      serumEventQueue: new PublicKey('99Cd6D9QnFfTdKpcwtoF3zAZdQAuZQi5NsPMERresj1r'),
      serumTknVault: new PublicKey('EBRqW7DaUGFBHRbfgRagpSf9jTSS3yp9MAi3RvabdBGz'),
      serumUsdcVault: new PublicKey('9QTMfdkgPWqLriB9J7FcYvroUEqfw6zW2VCi1dAabdUt'),
      serumVaultSigner: new PublicKey('HKt6xFufxTBBs719WQPbro9t1DfDxffurxFhTPntMgoe'),
      stakePoolProgramId: STAKE_PROGRAM_ID_V5,
      stakePoolId: new PublicKey('JAP8SFagJBm6vt2LoFGNeSJ1hKDZ2p3yXb3CvBx11How'),
      stakePoolAuthority: new PublicKey('DVtR63sAnJPM9wdt1hYBqA5GTyFzjfcfdLTfsSzV85Ss'),
      stakePoolLpAccount: new PublicKey('feCzxSvVX4EboJV4cubjqoPTK41noaHUanz8ZNJmiBp'),
      stakePoolRewardAccount: new PublicKey('4mAhgUY8XGMY4743wuzVbLw7d5bqqTaxME8jmbC2YfH4'),
      stakePoolRewardAccountB: new PublicKey('3sGDa8ir8GrkKbnBH6HP63JaYSs7nskmmVHpF2vuzaZr')
    }
  },
  'TULIP-USDC': {
    strategyAccount: new PublicKey('CfN7nPeFvvhRo5G6WkkH13eGADPpzyZhw1ofDT59rRFy'),
    strategyAuthority: new PublicKey('56rwPc9tGe8gLWvMPNaE6cxiWrC5i6695rHu56oxb3rJ'),
    strategyTknAccount: new PublicKey('FRjHb2JCHubudiNs8ai2H1VgfeCQfYqnURT3q3te4Y96'),
    strategyUsdcAccount: new PublicKey('BK5pB64VYSLAJNRvNZfs1CzGun7DFGAAfZoHSYZEFbDp'),
    strategyRayAccount: new PublicKey('3cWb7aHnnpEPjs1VvJvtc84gLbQYoruSZu5ip7T4P8Dv'),
    strategyLpAccount: new PublicKey('5KYjS3sh78j8Y9kRKgUz84Qr4EJqXNWaZybmfeajQwTS'),
    strategyFarmInfoAccount: new PublicKey('DcsUVhQ4jxpo6vQfnzWL126RHfMnryDnbngwLgg6vFNr'),
    strategyBorrowCreditAccount: new PublicKey('8DWkKJMFTU3wNmwjCD9y1n9xupCs2pzdXMtUSaN5qFoA'),
    programId: franciumProgramId,
    token1Mint: new PublicKey("EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"), // usdc
    token2Mint: new PublicKey("TuLipcqtGVXP9XR62wM8WWCm6a9vhLs7T1uoWBk6FDs"),
    lpMint: new PublicKey("2doeZGLJyACtaG9DCUyqMLtswesfje1hjNA11hMdj6YU"),
    raydiumInfo: {
      raydiumProgramId: LIQUIDITY_POOL_PROGRAM_ID_V4,
      ammId: new PublicKey('96hPvuJ3SRT82m7BAc7G1AUVPVcoj8DABAa5gT7wjgzX'),
      ammAuthority: new PublicKey('5Q544fKrFoe6tsEbD7S8EmxGTJYAKtTVhAW5Q5pge4j1'),
      ammOpenOrders: new PublicKey('6GtSWZfdUFtT47RPk2oSxoB6RbNkp9aM6yP77jB4XmZB'),
      ammTargetOrders: new PublicKey('9mB928abAihkhqM6AKLMW4cZkHBXFn2TmcxEKhTqs6Yr'),
      lpMintAccount: new PublicKey("2doeZGLJyACtaG9DCUyqMLtswesfje1hjNA11hMdj6YU"),
      lpDecimals: 6,
      ammTknAccount: new PublicKey('s9Xp7GV1jGvixdSfY6wPgivsTd3c4TzjW1eJGyojwV4'),
      ammUsdcAccount: new PublicKey('wcyW58QFNfppgm4Wi7cKhSftdVNfpLdn67YvvCNMWrt'),
      poolWithdrawQueue: new PublicKey('59NA3khShyZk4dhDjFN564nScNdEi3UR4wrCnLN6rRgX'),
      poolTempLpTokenAccount: new PublicKey('71oLQgsHknJVHGJDCaBVUnb6udGepK7kwkHXGy47u2i4'),
      serumProgramId: SERUM_PROGRAM_ID_V3,
      serumMarketId: new PublicKey('8GufnKq7YnXKhnB3WNhgy5PzU9uvHbaaRrZWQK6ixPxW'),
      serumBids: new PublicKey('69W6zLetZ7FgXPXgHRp4i4wNd422tXeZzDuBzdkjgoBW'),
      serumAsks: new PublicKey('42RcphsKYsVWDhaqJRETmx74RHXtHJDjZLFeeDrEL2F9'),
      serumEventQueue: new PublicKey('ExbLY71YpFaAGKuHjJKXSsWLA8hf1hGLoUYHNtzvbpGJ'),
      serumTknVault: new PublicKey('6qH3FNTSGKw34SEEj7GXbQ6kMQXHwuyGsAAeV5hLPhJc'),
      serumUsdcVault: new PublicKey('6AdJbeH76BBSJ34DeQ6LLdauF6W8fZRrMKEfLt3YcMcT'),
      serumVaultSigner: new PublicKey('5uJEd4wfVH84HyFEBf5chfJMTTPHBddXi1S7GmBE6x14'),
      stakePoolProgramId: STAKE_PROGRAM_ID_V5,
      stakePoolId: new PublicKey('7U8Z6TWQMtsMcHV2htALnF9VQonnD1MrVm17YtmGEGEw'),
      stakePoolAuthority: new PublicKey('9ZVNLEiBZ2u23P7rEJf5sXY7TZK723cmVs46pBRSbRnU'),
      stakePoolLpAccount: new PublicKey('B6xn6doS3Qfy1LJLbdcJa5MpJ4po2bgut1rKFvmmq6Ut'),
      stakePoolRewardAccount: new PublicKey('GtPTgCr6nXiogRCWqGvLa8P6dJgZpHfAX3KxGMpxnGMJ'),
      stakePoolRewardAccountB: new PublicKey('8qgijAifBGx2EAJ7zKAzk6z7dVpcDV9eHvTBwofmdTP5')
    }
  },
  'SNY-USDC': {
    strategyAccount: new PublicKey('GZHHYCMRA1R5GR8hphmqgyVTziKfxjPqqqvpBzCni2e2'),
    strategyAuthority: new PublicKey('5WoKzZrorGZiqynUbQjGGad448rydiS6joK8pVwkKAVD'),
    strategyTknAccount: new PublicKey('J3x5NZYwXf6ZoYB8VZAVfi9RcV7jt2uaZo8BQwYcD5ra'),
    strategyUsdcAccount: new PublicKey('8vrnRqU5N5HjUBce4q8vzh5AHaxKWQ5X3nfEGTjvzACu'),
    strategyRayAccount: new PublicKey('GiGjWgZgEePf8YrCyLkJth3QNC7QvhyKyXci4AeTsZS7'),
    strategyLpAccount: new PublicKey('5LdbaGydsyhAuEhSNW2vdHGJCM9neBJSgT2VcR5U2mqS'),
    strategyFarmInfoAccount: new PublicKey('EYsEyw1TCLwd5yKdwU2EiQo7zsZi3APf7uAmbtcSB8tK'),
    strategyBorrowCreditAccount: new PublicKey('CGQtZmqMsM4RCQPnSNRsXQrMdPuwFm1e9KwkdXsevMRX'),
    programId: franciumProgramId,
    token1Mint: new PublicKey("EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"), // usdc
    token2Mint: new PublicKey("4dmKkXNHdgYsXqBHCuMikNQWwVomZURhYvkkX5c4pQ7y"),
    lpMint: new PublicKey("G8qcfeFqxwbCqpxv5LpLWxUCd1PyMB5nWb5e5YyxLMKg"),
    raydiumInfo: {
      raydiumProgramId: LIQUIDITY_POOL_PROGRAM_ID_V4,
      ammId: new PublicKey('5TgJXpv6H3KJhHCuP7KoDLSCmi8sM8nABizP7CmYAKm1'),
      ammAuthority: new PublicKey('5Q544fKrFoe6tsEbD7S8EmxGTJYAKtTVhAW5Q5pge4j1'),
      ammOpenOrders: new PublicKey('2Nr82a2ZxqsQYwBbpeLWQedy1s9kAi2U2AbeuMKjgFzw'),
      ammTargetOrders: new PublicKey('Cts3uDVAgUSaXAHMEfLPnQWF4W5TpGdiB7WhYDAaQbSy'),
      lpMintAccount: new PublicKey('G8qcfeFqxwbCqpxv5LpLWxUCd1PyMB5nWb5e5YyxLMKg'),
      lpDecimals: 6,
      ammTknAccount: new PublicKey('FaUYbopmMVdNRe3rLnqGPBA2KB96nLHudKaEgAUcvHXn'),
      ammUsdcAccount: new PublicKey('9YiW8N9QdEsAdTQN8asjebwwEmDXAHRnb1E3nvz64vjg'),
      poolWithdrawQueue: new PublicKey('HpWzYHXNeQkmW9oxFjHFozyy6sVxetqJBZdhNSTwcNid'),
      poolTempLpTokenAccount: new PublicKey('7QAVG74PVZntmFqvnGYwYySRBjB13HSeSNABwMPtfAPR'),
      serumProgramId: SERUM_PROGRAM_ID_V3,
      serumMarketId: new PublicKey('DPfj2jYwPaezkCmUNm5SSYfkrkz8WFqwGLcxDDUsN3gA'),
      serumBids: new PublicKey('CFFoYkeUJaAEh6kQyVEbAgkWfABnH7c8Lynr2hk8ycJT'),
      serumAsks: new PublicKey('AVQEVeftGzTV6Yj2jEPFGgWHyTYs5uyT3ZFFyTaLgTAP'),
      serumEventQueue: new PublicKey('H6UE5r8zMsaHW9fha6Xm7bsWrYbyaL8WbBjhbqbZYPQM'),
      serumTknVault: new PublicKey('CddTJJj2tDWUk6Kteh3KSBJJh4HvkoWMXcQjZuXaaAzP'),
      serumUsdcVault: new PublicKey('BGr1LWgHKaekkmScogSU1SYSRUaJBBPFeBAEBvuwf7CE'),
      serumVaultSigner: new PublicKey('3APrMUDUQ16iEsL4vTaovTf5fPXAEwtXmWXvD9xQVPaB'),
      stakePoolProgramId: STAKE_PROGRAM_ID_V5,
      stakePoolId: new PublicKey('31QSh1TwgoA9GbvkgfEEwKEm11t8CR4KiQr6WCyJr7EN'),
      stakePoolAuthority: new PublicKey('BbebocNt4ySwkufrY1X3wRG8PVefCRLFR2E2TGzZPkne'),
      stakePoolLpAccount: new PublicKey('2t1qozn7xtWjuCqnnTx4PaKikajN2AQK3CVH6A5JqagY'),
      stakePoolRewardAccount: new PublicKey('GXZq2zNPZ9odPWAPinxXK8B7cMaAN9CpbcaLicksJsbt'),
      stakePoolRewardAccountB: new PublicKey('DdSL2stD9UXfY2nj9MKrNPx8QTro1GGAY6rsBd9kJXMX')
    }
  },
  'SLRS-USDC': {
    strategyAccount: new PublicKey('HyKQpxiKEhEt7dLVhcyMSwXFkhAhDHuaTreRstbkQH7j'),
    strategyAuthority: new PublicKey('GJK8g24YGmCFKL3ig2p8xkh8JUetbBwDSCtk1cisvSCe'),
    strategyTknAccount: new PublicKey('BES8QDp4iV3ZLnrzq3wgWjNfzyfhijfNCX2pmccPSgKa'),
    strategyUsdcAccount: new PublicKey('7FmgjkxVKxAvaDK5btm3QgotBaZXWvmgM8izujN5QRRy'),
    strategyRayAccount: new PublicKey('6DaFbM1BvSNphDerrAAsUJbgkrUECKv6NzKft2hygMg5'),
    strategyLpAccount: new PublicKey('Fs4gJRhFujRTsqFPWsMTQy4yQE72jd5LLLgKW82oQ6D1'),
    strategyFarmInfoAccount: new PublicKey('8X2rbhn3L2RP8FtjxdgVi1jbz5WEhCtMWT4VKVcs6uMZ'),
    strategyBorrowCreditAccount: new PublicKey('4NM8oRvJKGCZKsNFz17VwXoHJVFkteUcwbfnKxg7Uehs'),
    programId: franciumProgramId,
    token1Mint: new PublicKey("EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"), // usdc
    token2Mint: new PublicKey('SLRSSpSLUTP7okbCUBYStWCo1vUgyt775faPqz8HUMr'),
    lpMint: new PublicKey("2Xxbm1hdv5wPeen5ponDSMT3VqhGMTQ7mH9stNXm9shU"),
    raydiumInfo: {
      raydiumProgramId: LIQUIDITY_POOL_PROGRAM_ID_V4,
      ammId: new PublicKey('7XXKU8oGDbeGrkPyK5yHKzdsrMJtB7J2TMugjbrXEhB5'),
      ammAuthority: new PublicKey('5Q544fKrFoe6tsEbD7S8EmxGTJYAKtTVhAW5Q5pge4j1'),
      ammOpenOrders: new PublicKey('3wNRVMaot3R2piZkzmKsAqewcZ5ABktqrJZrc4Vz3uWs'),
      ammTargetOrders: new PublicKey('BwSmQF7nxRqzzVdfaynxM98dNbXFi94cemDDtxMfV3SB'),
      lpMintAccount: new PublicKey("2Xxbm1hdv5wPeen5ponDSMT3VqhGMTQ7mH9stNXm9shU"),
      lpDecimals: 6,
      ammTknAccount: new PublicKey('6vjnbp6vhw4RxNqN3e2tfE3VnkbCx8RCLt8RBmHZvuoC'),
      ammUsdcAccount: new PublicKey('2anKifuiizorX69zWQddupMqawGfk3TMPGZs4t7ZZk43'),
      poolWithdrawQueue: new PublicKey('Fh5WTfP9jCbkLPzsspCs4WCSPGqE5GYE8v7kqFXijMSA'),
      poolTempLpTokenAccount: new PublicKey('9oiniKrJ7r1cHw97gv4XPxTFS9i61vSa7PkpRcm8qGeK'),
      serumProgramId: SERUM_PROGRAM_ID_V3,
      serumMarketId: new PublicKey('2Gx3UfV831BAh8uQv1FKSPKS9yajfeeD8GJ4ZNb2o2YP'),
      serumBids: new PublicKey('6kMW5vafM4mWZJdBNpH4EsVjFSuSTUokx5meYoVY8GTw'),
      serumAsks: new PublicKey('D5asu2BVatxtgGFugwmNubdknAsLSJDZcqRHvkaS8UBd'),
      serumEventQueue: new PublicKey('66Go3JcjNJaDHHvJyaFaV8rh8GAciLzvM8WzN7fRE3HM'),
      serumTknVault: new PublicKey('6B527pfkvbvbLRDgjASLGygdaQ1fFLwmmqyFCgTacsKH'),
      serumUsdcVault: new PublicKey('Bsa11vdveUhSouxAXSYCE4yXToUP58N9EEeM1P8qbtp3'),
      serumVaultSigner: new PublicKey('CjiJdQ9a7dnjTKfVPZ2fwn31NtgJA1kRU55pwDE8HHrM'),
      stakePoolProgramId: STAKE_PROGRAM_ID_V5,
      stakePoolId: new PublicKey('5PVVwSqwzkCvuiKEZwWkM35ApBnoWqF8XopsVZjPwA8z'),
      stakePoolAuthority: new PublicKey('7jNUxDiLLyke8ECShavvPPQz4D1abj4aCZwQfZ3TCTAX'),
      stakePoolLpAccount: new PublicKey('HTr2pYDBQZP13YTzLdsPzmh6e4hsNeqoGy3B777ejqTT'),
      stakePoolRewardAccount: new PublicKey('Ef1tQ2E2Fe92xPVpQGzZFHmT7g7dh2hzVfWYVJJQPdbu'),
      stakePoolRewardAccountB: new PublicKey('Ffmv9Ximzk8D9oKwHkkgdq9cVxv5P5Y9LxEJdu1N1jSJ'),
    }
  },
  'STEP-USDC': {
    strategyAccount: new PublicKey('6ZAdLxkXmgezDqfJFVabAUoqDh5qktMFXfVwd6szBEPV'),
    strategyAuthority: new PublicKey('BRpw5RP1Cjb5YcMDxJzQfodhsKE6vNkJmq3Y1KH7tqiN'),
    strategyTknAccount: new PublicKey('7kdBwHZbziNnNF8KRUiwxewdHo5pU6iAXGFYNyX4T8KE'),
    strategyUsdcAccount: new PublicKey('DhmZKUq6NC9nbM9oan9fG42WXQofr1pofvHGHQJcH85n'),
    strategyRayAccount: new PublicKey('5PteDhGdRnxRaiqD1o9ZEgfhZHGQJdY58NvJMwsqcJg3'),
    strategyLpAccount: new PublicKey('Fps5ZypoAMgibcVksLvp5FD66NSDf9ySJj2JcLpD8yVg'),
    strategyFarmInfoAccount: new PublicKey('6DiR3uYkEeYkYTF5KT98Q6V6191988KuDeyzDg4K1qu5'),
    strategyBorrowCreditAccount: new PublicKey('HYconnvcfxL8AJQagTXVNETi27Au1zYJ7aLR3SVCS3tM'),
    programId: franciumProgramId,
    token1Mint: new PublicKey("EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"), // usdc
    token2Mint: new PublicKey("StepAscQoEioFxxWGnh2sLBDFp9d8rvKz2Yp39iDpyT"),
    lpMint: new PublicKey("3k8BDobgihmk72jVmXYLE168bxxQUhqqyESW4dQVktqC"),
    raydiumInfo: {
      raydiumProgramId: LIQUIDITY_POOL_PROGRAM_ID_V4,
      ammId: new PublicKey('4Sx1NLrQiK4b9FdLKe2DhQ9FHvRzJhzKN3LoD6BrEPnf'),
      ammAuthority: new PublicKey('5Q544fKrFoe6tsEbD7S8EmxGTJYAKtTVhAW5Q5pge4j1'),
      ammOpenOrders: new PublicKey('EXgME2sUuzBxEc2wuyoSZ8FZNZMC3ChhZgFZRAW3nCQG'),
      ammTargetOrders: new PublicKey('78bwAGKJjaiPQqmwKmbj4fhrRTLAdzwqNwpFdpTzrhk1'),
      lpMintAccount: new PublicKey("3k8BDobgihmk72jVmXYLE168bxxQUhqqyESW4dQVktqC"),
      lpDecimals: 9,
      ammTknAccount: new PublicKey('8Gf8Cc6yrxtfUZqM2vf2kg5uR9bGPfCHfzdYRVBAJSJj'),
      ammUsdcAccount: new PublicKey('ApLc86fHjVbGbU9QFzNPNuWM5VYckZM92q6sgJN1SGYn'),
      poolWithdrawQueue: new PublicKey('5bzBcB7cnJYGYvGPFxKcZETn6sGAyBbXgFhUbefbagYh'),
      poolTempLpTokenAccount: new PublicKey('CpfWKDYNYfvgk42tqR8HEHUWohGSJjASXfRBm3yaKJre'),
      serumProgramId: SERUM_PROGRAM_ID_V3,
      serumMarketId: new PublicKey('97qCB4cAVSTthvJu3eNoEx6AY6DLuRDtCoPm5Tdyg77S'),
      serumBids: new PublicKey('5Xdpf7CMGFDkJj1smcVQAAZG6GY9gqAns18QLKbPZKsw'),
      serumAsks: new PublicKey('6Tqwg8nrKJrcqsr4zR9wJuPv3iXsHAMN65FxwJ3RMH8S'),
      serumEventQueue: new PublicKey('5frw4m8pEZHorTKVzmMzvf8xLUrj65vN7wA57KzaZFK3'),
      serumTknVault: new PublicKey('CVNye3Xr9Jv26c8TVqZZHq4F43BhoWWfmrzyp1M9YA67'),
      serumUsdcVault: new PublicKey('AnGbReAhCDFkR83nB8mXTDX5dQJFB8Pwicu6pGMfCLjt'),
      serumVaultSigner: new PublicKey('FbwU5U1Doj2PSKRJi7pnCny4dFPPJURwALkFhHwdHaMW'),
      stakePoolProgramId: STAKE_PROGRAM_ID_V5,
      stakePoolId: new PublicKey('8xhjCzfzVcP79jE7jXR2xtNaSL6aJYoDRLVT9FMjpRTC'),
      stakePoolAuthority: new PublicKey('6wRMPrHKFzj3qB4j5yj4y9mDF89fZ6w7gD1cEzCJwT9B'),
      stakePoolLpAccount: new PublicKey('CP3wdgdSygYGLJMjKfbJMiANnYuAxXHPiLTtB124tzVX'),
      stakePoolRewardAccount: new PublicKey('3zSiR4XrrRPhsom2hh9iigYZZ7uCpMucfJnZRgREgH8j'),
      stakePoolRewardAccountB: new PublicKey('4n3vRUk3wdtbGWgMFSaxUcnGLKwa2wiWVhqw7kv9JDVS')
    }
  },
  'LIKE-USDC': {
    strategyAccount: new PublicKey('HBYjgQt7URusKTMrfZhzqJ9VNsvEBT8nGhYcb53YGd4n'),
    strategyAuthority: new PublicKey('EJJ6tTgUCuDskGgasPqfze9adR8Cf9RqpLmUkDX3ipR3'),
    strategyTknAccount: new PublicKey('EvTLNBHfHx8wsijgYgbjsHSfYezRWkK3UeRWuwkViutJ'),
    strategyUsdcAccount: new PublicKey('EotgpUxz1Lzhr8GFiYbLDUbrvUBakmSGN73eKHm8ayTV'),
    strategyRayAccount: new PublicKey('FWtHR76wE6Taok9bXNvFhTfEVpMWaNNSe5QLMnxs1oU8'),
    strategyLpAccount: new PublicKey('C9mTxHXBMD5DY7PgCySNT4C4iDsWETgMxJvvboDKUiQA'),
    strategyFarmInfoAccount: new PublicKey('45VRt7nk95pnpgYtZH5Cy7ag6bTFUA9DzgDni3icdh61'),
    strategyBorrowCreditAccount: new PublicKey('9AR8uSTyc7yscMFXLq6PsiPr9T5S4EPUGQzPyP1VLXsC'), programId: franciumProgramId,
    token1Mint: new PublicKey("EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"), // usdc
    token2Mint: new PublicKey('3bRTivrVsitbmCTGtqwp7hxXPsybkjn4XLNtPsHqa3zR'),
    lpMint: new PublicKey("cjZmbt8sJgaoyWYUttomAu5LJYU44ZrcKTbzTSEPDVw"),
    raydiumInfo: {
      raydiumProgramId: LIQUIDITY_POOL_PROGRAM_ID_V4,
      ammId: new PublicKey('GmaDNMWsTYWjaXVBjJTHNmCWAKU6cn5hhtWWYEZt4odo'),
      ammAuthority: new PublicKey('5Q544fKrFoe6tsEbD7S8EmxGTJYAKtTVhAW5Q5pge4j1'),
      ammOpenOrders: new PublicKey('Crn5beRFeyj4Xw13E2wdJ9YkkLLEZzKYmtTV4LFDx3MN'),
      ammTargetOrders: new PublicKey('7XjS6MrvBRi9JeFWBMAYPaKhKgR3b7xnVdYDBkFb4CXR'),
      lpMintAccount: new PublicKey("cjZmbt8sJgaoyWYUttomAu5LJYU44ZrcKTbzTSEPDVw"),
      lpDecimals: 9,
      ammTknAccount: new PublicKey('8LoHX6f6bMdQVs4mThoH2KwX2dQDSkqVFADi4ZjDQv9T'),
      ammUsdcAccount: new PublicKey('2Fwm8M8vuPXEXxvKz98VdawDxsK9W8uRuJyJhvtRdhid'),
      poolWithdrawQueue: new PublicKey('CW9zJ2JbBekkdd5SdvPapPcbziR8d1UHBzW7nNn1W3ga'),
      poolTempLpTokenAccount: new PublicKey('FVHsnC1nhwMcrAzFwcK4dgUtDdYFM1VrTJ8Rp8Mb1LkY'),
      serumProgramId: SERUM_PROGRAM_ID_V3,
      serumMarketId: new PublicKey('3WptgZZu34aiDrLMUiPntTYZGNZ72yT1yxHYxSdbTArX'),
      serumBids: new PublicKey('GzHpnQSfS7KdqLKgiEEP7pkYnwEBz9zaE7De2CjmCrNV'),
      serumAsks: new PublicKey('FpEBAT9qP1so4ASUTiEWxyXH2SJvgoBYUiZ1AbPimcS7'),
      serumEventQueue: new PublicKey('CUMDMV9KtE22RUZECUNHxiq7FmUiRusyKa1rHUJfRptq'),
      serumTknVault: new PublicKey('Dd9F1fugQj2xtduyNvFS5TtxP9vKnuxVMcrPsHFnLyqp'),
      serumUsdcVault: new PublicKey('BnXXu8kLUXrwg3MpcVRVPLZw9bpX2mLd95qtCMnSUtu7'),
      serumVaultSigner: new PublicKey('MKCHeoqNGWU8TJBkdF1M76nMUteJCwuBRUJfCtR3iV7'),
      stakePoolProgramId: STAKE_PROGRAM_ID_V5,
      stakePoolId: new PublicKey('BRM5bdX2mjmFGg2RAent1Whd61o9asQD16BXsC6QvEni'),
      stakePoolAuthority: new PublicKey('9rThpjxEgNR5xi2z2QgXenS2RwRrrN1GqrudegT32Ygy'),
      stakePoolLpAccount: new PublicKey('FzVu8n4UCf3o1KH4X8khM9KgKA96dJQdQMPtLvmbHyNi'),
      stakePoolRewardAccount: new PublicKey('3G1cbktUU79CT3zskP16VYmEhwVQq2RYxVWV7fcjmkTX'),
      stakePoolRewardAccountB: new PublicKey('2Ks41qfN2GZffbd1cqrNGuXJYJbShHhz6aHQvq8SaYYr'),
    }
  },
  'MNGO-USDC': {
    strategyAccount: new PublicKey('AxYB79zFZaF4AVPicx6DJH9XCuh9A5GXmt7MYsEoiaur'),
    strategyAuthority: new PublicKey('5VUW3MR3vU8E6LwEmUxU9Ac8baoYdGKevznESRuwfBcb'),
    strategyTknAccount: new PublicKey('3iQrTYv9qVaqktefn7nJCScZAXm2hKNZsMAg2Hwg2gMJ'),
    strategyUsdcAccount: new PublicKey('GNf9K7y1YV8Q19PPUfAzcm5ZGrA4qRokPAmDcAD7C3U4'),
    strategyRayAccount: new PublicKey('31xy2uxnxa6NjXFtehGGzMeFrJdQHybisMgHFQHaJDcV'),
    strategyLpAccount: new PublicKey('GZGNzSPNDPPJ3w9kfwNUz66i5MAsQKMWwzPh17eji4hq'),
    strategyFarmInfoAccount: new PublicKey('Axfi5ic8yGNELJbD4Ek6XFCWUKnSGGnXDFatMBgynbLA'),
    strategyBorrowCreditAccount: new PublicKey('EDcZp7N4EzuCGhdWGxfvKKw6bvJgX9cZeSaLECfNbTfy'), programId: franciumProgramId,
    token1Mint: new PublicKey("EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"), // usdc
    token2Mint: new PublicKey('MangoCzJ36AjZyKwVj3VnYU4GTonjfVEnJmvvWaxLac'),
    lpMint: new PublicKey("DkiqCQ792n743xjWQVCbBUaVtkdiuvQeYndM53ReWnCC"),
    raydiumInfo: {
      raydiumProgramId: LIQUIDITY_POOL_PROGRAM_ID_V4,
      ammId: new PublicKey('34tFULRrRwh4bMcBLPtJaNqqe5pVgGZACi5sR8Xz95KC'),
      ammAuthority: new PublicKey('5Q544fKrFoe6tsEbD7S8EmxGTJYAKtTVhAW5Q5pge4j1'),
      ammOpenOrders: new PublicKey('58G7RrYRntVvVj9rVgDwGhAJoWhMWHNyDCoMydYUwSR6'),
      ammTargetOrders: new PublicKey('2qBcjDqDywhB7Kgb1VYq8K5svJh37BB8oC5kBE4VqA7q'),
      lpMintAccount: new PublicKey("DkiqCQ792n743xjWQVCbBUaVtkdiuvQeYndM53ReWnCC"),
      lpDecimals: 6,
      ammTknAccount: new PublicKey('91fMidHL8Yr8KRcu4Zu2RPRRg1FbXxZ7DV43rAyKRLjn'),
      ammUsdcAccount: new PublicKey('93oFfbcayY2WkcR6d9AyqPcRC121dXmWarFJkwPErRRE'),
      poolWithdrawQueue: new PublicKey('FhnSdMoRPj75bLs6yzaDPFfiuucUZhVDiyM78WEhaKJo'),
      poolTempLpTokenAccount: new PublicKey('FZAwAb6UxNiwDTbQZ3bPKYA4PkbYpurh8YpAH8G424Lv'),
      serumProgramId: SERUM_PROGRAM_ID_V3,
      serumMarketId: new PublicKey('3d4rzwpy9iGdCZvgxcu7B1YocYffVLsQXPXkBZKt2zLc'),
      serumBids: new PublicKey('3nAdH9wTEhPoW4e2s8K2cXfn4jZH8FBCkUqtzWpsZaGb'),
      serumAsks: new PublicKey('HxbWm3iabHEFeHG9LVGYycTwn7aJVYYHbpQyhZhAYnfn'),
      serumEventQueue: new PublicKey('H1VVmwbM96BiBJq46zubSBm6VBhfM2FUhLVUqKGh1ee9'),
      serumTknVault: new PublicKey('7Ex7id4G37HynuiCAv5hTYM4BnPB9y4NU85QcaNWZy3G'),
      serumUsdcVault: new PublicKey('9UB1NhGeDuV1apHdtK5LeAEjP7kZFH8vVYGdh2yGFRi8'),
      serumVaultSigner: new PublicKey('BFkxdUwW17eANhfs1xNmBqEcegb4EStQxVb5VaMS2dq6'),
      stakePoolProgramId: STAKE_PROGRAM_ID_V5,
      stakePoolId: new PublicKey('GzEDEkHSFFfxKMu3Toww1nrEjtbQGJKRPNRK1Pfd59Zn'),
      stakePoolAuthority: new PublicKey('9AMvw1TUJ9gX1kUAvcmHt2ZjokBLepXQbN8EJxBVZu2s'),
      stakePoolLpAccount: new PublicKey('gjrMLKsNwXYzJnX9DT8Lc7HeC1AT52jQKtDkPiRRuEP'),
      stakePoolRewardAccount: new PublicKey('4czqUC2ebdvqxPXfRniknLk7Cr2TosTabQSRnUeFia9v'),
      stakePoolRewardAccountB: new PublicKey('6K1AE1wnTNaMgcAgQPvrTbnWEHB7nW6uTtv7ZbXWgMtn')
    }
  }
};